// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: classification/ftrl/internal/internal.proto

package com.blacksquaremedia.reason.classification;

public final class FTRLProtos {
  private FTRLProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OptimizerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:blacksquaremedia.reason.classification.ftrl.Optimizer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The underlying model.
     * </pre>
     *
     * <code>.blacksquaremedia.reason.core.Model model = 1;</code>
     */
    boolean hasModel();
    /**
     * <pre>
     * The underlying model.
     * </pre>
     *
     * <code>.blacksquaremedia.reason.core.Model model = 1;</code>
     */
    com.blacksquaremedia.reason.CoreProtos.Model getModel();
    /**
     * <pre>
     * The underlying model.
     * </pre>
     *
     * <code>.blacksquaremedia.reason.core.Model model = 1;</code>
     */
    com.blacksquaremedia.reason.CoreProtos.ModelOrBuilder getModelOrBuilder();

    /**
     * <pre>
     * The target feature.
     * </pre>
     *
     * <code>string target = 2;</code>
     */
    java.lang.String getTarget();
    /**
     * <pre>
     * The target feature.
     * </pre>
     *
     * <code>string target = 2;</code>
     */
    com.google.protobuf.ByteString
        getTargetBytes();

    /**
     * <pre>
     * The gradient sums.
     * </pre>
     *
     * <code>repeated double sums = 3;</code>
     */
    java.util.List<java.lang.Double> getSumsList();
    /**
     * <pre>
     * The gradient sums.
     * </pre>
     *
     * <code>repeated double sums = 3;</code>
     */
    int getSumsCount();
    /**
     * <pre>
     * The gradient sums.
     * </pre>
     *
     * <code>repeated double sums = 3;</code>
     */
    double getSums(int index);

    /**
     * <pre>
     * The weights.
     * </pre>
     *
     * <code>repeated double weights = 4;</code>
     */
    java.util.List<java.lang.Double> getWeightsList();
    /**
     * <pre>
     * The weights.
     * </pre>
     *
     * <code>repeated double weights = 4;</code>
     */
    int getWeightsCount();
    /**
     * <pre>
     * The weights.
     * </pre>
     *
     * <code>repeated double weights = 4;</code>
     */
    double getWeights(int index);
  }
  /**
   * <pre>
   * Optimizer wraps the optimizer data.
   * </pre>
   *
   * Protobuf type {@code blacksquaremedia.reason.classification.ftrl.Optimizer}
   */
  public  static final class Optimizer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:blacksquaremedia.reason.classification.ftrl.Optimizer)
      OptimizerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Optimizer.newBuilder() to construct.
    private Optimizer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Optimizer() {
      target_ = "";
      sums_ = java.util.Collections.emptyList();
      weights_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Optimizer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.blacksquaremedia.reason.CoreProtos.Model.Builder subBuilder = null;
              if (model_ != null) {
                subBuilder = model_.toBuilder();
              }
              model_ = input.readMessage(com.blacksquaremedia.reason.CoreProtos.Model.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(model_);
                model_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              target_ = s;
              break;
            }
            case 25: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                sums_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000004;
              }
              sums_.add(input.readDouble());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                sums_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                sums_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 33: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                weights_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000008;
              }
              weights_.add(input.readDouble());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                weights_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                weights_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          sums_ = java.util.Collections.unmodifiableList(sums_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          weights_ = java.util.Collections.unmodifiableList(weights_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blacksquaremedia.reason.classification.FTRLProtos.internal_static_blacksquaremedia_reason_classification_ftrl_Optimizer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blacksquaremedia.reason.classification.FTRLProtos.internal_static_blacksquaremedia_reason_classification_ftrl_Optimizer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer.class, com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer.Builder.class);
    }

    private int bitField0_;
    public static final int MODEL_FIELD_NUMBER = 1;
    private com.blacksquaremedia.reason.CoreProtos.Model model_;
    /**
     * <pre>
     * The underlying model.
     * </pre>
     *
     * <code>.blacksquaremedia.reason.core.Model model = 1;</code>
     */
    public boolean hasModel() {
      return model_ != null;
    }
    /**
     * <pre>
     * The underlying model.
     * </pre>
     *
     * <code>.blacksquaremedia.reason.core.Model model = 1;</code>
     */
    public com.blacksquaremedia.reason.CoreProtos.Model getModel() {
      return model_ == null ? com.blacksquaremedia.reason.CoreProtos.Model.getDefaultInstance() : model_;
    }
    /**
     * <pre>
     * The underlying model.
     * </pre>
     *
     * <code>.blacksquaremedia.reason.core.Model model = 1;</code>
     */
    public com.blacksquaremedia.reason.CoreProtos.ModelOrBuilder getModelOrBuilder() {
      return getModel();
    }

    public static final int TARGET_FIELD_NUMBER = 2;
    private volatile java.lang.Object target_;
    /**
     * <pre>
     * The target feature.
     * </pre>
     *
     * <code>string target = 2;</code>
     */
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        target_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The target feature.
     * </pre>
     *
     * <code>string target = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUMS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Double> sums_;
    /**
     * <pre>
     * The gradient sums.
     * </pre>
     *
     * <code>repeated double sums = 3;</code>
     */
    public java.util.List<java.lang.Double>
        getSumsList() {
      return sums_;
    }
    /**
     * <pre>
     * The gradient sums.
     * </pre>
     *
     * <code>repeated double sums = 3;</code>
     */
    public int getSumsCount() {
      return sums_.size();
    }
    /**
     * <pre>
     * The gradient sums.
     * </pre>
     *
     * <code>repeated double sums = 3;</code>
     */
    public double getSums(int index) {
      return sums_.get(index);
    }
    private int sumsMemoizedSerializedSize = -1;

    public static final int WEIGHTS_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Double> weights_;
    /**
     * <pre>
     * The weights.
     * </pre>
     *
     * <code>repeated double weights = 4;</code>
     */
    public java.util.List<java.lang.Double>
        getWeightsList() {
      return weights_;
    }
    /**
     * <pre>
     * The weights.
     * </pre>
     *
     * <code>repeated double weights = 4;</code>
     */
    public int getWeightsCount() {
      return weights_.size();
    }
    /**
     * <pre>
     * The weights.
     * </pre>
     *
     * <code>repeated double weights = 4;</code>
     */
    public double getWeights(int index) {
      return weights_.get(index);
    }
    private int weightsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (model_ != null) {
        output.writeMessage(1, getModel());
      }
      if (!getTargetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, target_);
      }
      if (getSumsList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(sumsMemoizedSerializedSize);
      }
      for (int i = 0; i < sums_.size(); i++) {
        output.writeDoubleNoTag(sums_.get(i));
      }
      if (getWeightsList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(weightsMemoizedSerializedSize);
      }
      for (int i = 0; i < weights_.size(); i++) {
        output.writeDoubleNoTag(weights_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (model_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getModel());
      }
      if (!getTargetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, target_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getSumsList().size();
        size += dataSize;
        if (!getSumsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        sumsMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 8 * getWeightsList().size();
        size += dataSize;
        if (!getWeightsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        weightsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer)) {
        return super.equals(obj);
      }
      com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer other = (com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer) obj;

      boolean result = true;
      result = result && (hasModel() == other.hasModel());
      if (hasModel()) {
        result = result && getModel()
            .equals(other.getModel());
      }
      result = result && getTarget()
          .equals(other.getTarget());
      result = result && getSumsList()
          .equals(other.getSumsList());
      result = result && getWeightsList()
          .equals(other.getWeightsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasModel()) {
        hash = (37 * hash) + MODEL_FIELD_NUMBER;
        hash = (53 * hash) + getModel().hashCode();
      }
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getTarget().hashCode();
      if (getSumsCount() > 0) {
        hash = (37 * hash) + SUMS_FIELD_NUMBER;
        hash = (53 * hash) + getSumsList().hashCode();
      }
      if (getWeightsCount() > 0) {
        hash = (37 * hash) + WEIGHTS_FIELD_NUMBER;
        hash = (53 * hash) + getWeightsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Optimizer wraps the optimizer data.
     * </pre>
     *
     * Protobuf type {@code blacksquaremedia.reason.classification.ftrl.Optimizer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:blacksquaremedia.reason.classification.ftrl.Optimizer)
        com.blacksquaremedia.reason.classification.FTRLProtos.OptimizerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blacksquaremedia.reason.classification.FTRLProtos.internal_static_blacksquaremedia_reason_classification_ftrl_Optimizer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blacksquaremedia.reason.classification.FTRLProtos.internal_static_blacksquaremedia_reason_classification_ftrl_Optimizer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer.class, com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer.Builder.class);
      }

      // Construct using com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (modelBuilder_ == null) {
          model_ = null;
        } else {
          model_ = null;
          modelBuilder_ = null;
        }
        target_ = "";

        sums_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        weights_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blacksquaremedia.reason.classification.FTRLProtos.internal_static_blacksquaremedia_reason_classification_ftrl_Optimizer_descriptor;
      }

      public com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer getDefaultInstanceForType() {
        return com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer.getDefaultInstance();
      }

      public com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer build() {
        com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer buildPartial() {
        com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer result = new com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (modelBuilder_ == null) {
          result.model_ = model_;
        } else {
          result.model_ = modelBuilder_.build();
        }
        result.target_ = target_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          sums_ = java.util.Collections.unmodifiableList(sums_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.sums_ = sums_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          weights_ = java.util.Collections.unmodifiableList(weights_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.weights_ = weights_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer) {
          return mergeFrom((com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer other) {
        if (other == com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer.getDefaultInstance()) return this;
        if (other.hasModel()) {
          mergeModel(other.getModel());
        }
        if (!other.getTarget().isEmpty()) {
          target_ = other.target_;
          onChanged();
        }
        if (!other.sums_.isEmpty()) {
          if (sums_.isEmpty()) {
            sums_ = other.sums_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSumsIsMutable();
            sums_.addAll(other.sums_);
          }
          onChanged();
        }
        if (!other.weights_.isEmpty()) {
          if (weights_.isEmpty()) {
            weights_ = other.weights_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureWeightsIsMutable();
            weights_.addAll(other.weights_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.blacksquaremedia.reason.CoreProtos.Model model_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.blacksquaremedia.reason.CoreProtos.Model, com.blacksquaremedia.reason.CoreProtos.Model.Builder, com.blacksquaremedia.reason.CoreProtos.ModelOrBuilder> modelBuilder_;
      /**
       * <pre>
       * The underlying model.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Model model = 1;</code>
       */
      public boolean hasModel() {
        return modelBuilder_ != null || model_ != null;
      }
      /**
       * <pre>
       * The underlying model.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Model model = 1;</code>
       */
      public com.blacksquaremedia.reason.CoreProtos.Model getModel() {
        if (modelBuilder_ == null) {
          return model_ == null ? com.blacksquaremedia.reason.CoreProtos.Model.getDefaultInstance() : model_;
        } else {
          return modelBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The underlying model.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Model model = 1;</code>
       */
      public Builder setModel(com.blacksquaremedia.reason.CoreProtos.Model value) {
        if (modelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          model_ = value;
          onChanged();
        } else {
          modelBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * The underlying model.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Model model = 1;</code>
       */
      public Builder setModel(
          com.blacksquaremedia.reason.CoreProtos.Model.Builder builderForValue) {
        if (modelBuilder_ == null) {
          model_ = builderForValue.build();
          onChanged();
        } else {
          modelBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * The underlying model.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Model model = 1;</code>
       */
      public Builder mergeModel(com.blacksquaremedia.reason.CoreProtos.Model value) {
        if (modelBuilder_ == null) {
          if (model_ != null) {
            model_ =
              com.blacksquaremedia.reason.CoreProtos.Model.newBuilder(model_).mergeFrom(value).buildPartial();
          } else {
            model_ = value;
          }
          onChanged();
        } else {
          modelBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * The underlying model.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Model model = 1;</code>
       */
      public Builder clearModel() {
        if (modelBuilder_ == null) {
          model_ = null;
          onChanged();
        } else {
          model_ = null;
          modelBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The underlying model.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Model model = 1;</code>
       */
      public com.blacksquaremedia.reason.CoreProtos.Model.Builder getModelBuilder() {
        
        onChanged();
        return getModelFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The underlying model.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Model model = 1;</code>
       */
      public com.blacksquaremedia.reason.CoreProtos.ModelOrBuilder getModelOrBuilder() {
        if (modelBuilder_ != null) {
          return modelBuilder_.getMessageOrBuilder();
        } else {
          return model_ == null ?
              com.blacksquaremedia.reason.CoreProtos.Model.getDefaultInstance() : model_;
        }
      }
      /**
       * <pre>
       * The underlying model.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Model model = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.blacksquaremedia.reason.CoreProtos.Model, com.blacksquaremedia.reason.CoreProtos.Model.Builder, com.blacksquaremedia.reason.CoreProtos.ModelOrBuilder> 
          getModelFieldBuilder() {
        if (modelBuilder_ == null) {
          modelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.blacksquaremedia.reason.CoreProtos.Model, com.blacksquaremedia.reason.CoreProtos.Model.Builder, com.blacksquaremedia.reason.CoreProtos.ModelOrBuilder>(
                  getModel(),
                  getParentForChildren(),
                  isClean());
          model_ = null;
        }
        return modelBuilder_;
      }

      private java.lang.Object target_ = "";
      /**
       * <pre>
       * The target feature.
       * </pre>
       *
       * <code>string target = 2;</code>
       */
      public java.lang.String getTarget() {
        java.lang.Object ref = target_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          target_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The target feature.
       * </pre>
       *
       * <code>string target = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTargetBytes() {
        java.lang.Object ref = target_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          target_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The target feature.
       * </pre>
       *
       * <code>string target = 2;</code>
       */
      public Builder setTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The target feature.
       * </pre>
       *
       * <code>string target = 2;</code>
       */
      public Builder clearTarget() {
        
        target_ = getDefaultInstance().getTarget();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The target feature.
       * </pre>
       *
       * <code>string target = 2;</code>
       */
      public Builder setTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        target_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Double> sums_ = java.util.Collections.emptyList();
      private void ensureSumsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          sums_ = new java.util.ArrayList<java.lang.Double>(sums_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       * The gradient sums.
       * </pre>
       *
       * <code>repeated double sums = 3;</code>
       */
      public java.util.List<java.lang.Double>
          getSumsList() {
        return java.util.Collections.unmodifiableList(sums_);
      }
      /**
       * <pre>
       * The gradient sums.
       * </pre>
       *
       * <code>repeated double sums = 3;</code>
       */
      public int getSumsCount() {
        return sums_.size();
      }
      /**
       * <pre>
       * The gradient sums.
       * </pre>
       *
       * <code>repeated double sums = 3;</code>
       */
      public double getSums(int index) {
        return sums_.get(index);
      }
      /**
       * <pre>
       * The gradient sums.
       * </pre>
       *
       * <code>repeated double sums = 3;</code>
       */
      public Builder setSums(
          int index, double value) {
        ensureSumsIsMutable();
        sums_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The gradient sums.
       * </pre>
       *
       * <code>repeated double sums = 3;</code>
       */
      public Builder addSums(double value) {
        ensureSumsIsMutable();
        sums_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The gradient sums.
       * </pre>
       *
       * <code>repeated double sums = 3;</code>
       */
      public Builder addAllSums(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureSumsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sums_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The gradient sums.
       * </pre>
       *
       * <code>repeated double sums = 3;</code>
       */
      public Builder clearSums() {
        sums_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Double> weights_ = java.util.Collections.emptyList();
      private void ensureWeightsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          weights_ = new java.util.ArrayList<java.lang.Double>(weights_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <pre>
       * The weights.
       * </pre>
       *
       * <code>repeated double weights = 4;</code>
       */
      public java.util.List<java.lang.Double>
          getWeightsList() {
        return java.util.Collections.unmodifiableList(weights_);
      }
      /**
       * <pre>
       * The weights.
       * </pre>
       *
       * <code>repeated double weights = 4;</code>
       */
      public int getWeightsCount() {
        return weights_.size();
      }
      /**
       * <pre>
       * The weights.
       * </pre>
       *
       * <code>repeated double weights = 4;</code>
       */
      public double getWeights(int index) {
        return weights_.get(index);
      }
      /**
       * <pre>
       * The weights.
       * </pre>
       *
       * <code>repeated double weights = 4;</code>
       */
      public Builder setWeights(
          int index, double value) {
        ensureWeightsIsMutable();
        weights_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The weights.
       * </pre>
       *
       * <code>repeated double weights = 4;</code>
       */
      public Builder addWeights(double value) {
        ensureWeightsIsMutable();
        weights_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The weights.
       * </pre>
       *
       * <code>repeated double weights = 4;</code>
       */
      public Builder addAllWeights(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureWeightsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, weights_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The weights.
       * </pre>
       *
       * <code>repeated double weights = 4;</code>
       */
      public Builder clearWeights() {
        weights_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:blacksquaremedia.reason.classification.ftrl.Optimizer)
    }

    // @@protoc_insertion_point(class_scope:blacksquaremedia.reason.classification.ftrl.Optimizer)
    private static final com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer();
    }

    public static com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Optimizer>
        PARSER = new com.google.protobuf.AbstractParser<Optimizer>() {
      public Optimizer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Optimizer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Optimizer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Optimizer> getParserForType() {
      return PARSER;
    }

    public com.blacksquaremedia.reason.classification.FTRLProtos.Optimizer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blacksquaremedia_reason_classification_ftrl_Optimizer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blacksquaremedia_reason_classification_ftrl_Optimizer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+classification/ftrl/internal/internal." +
      "proto\022+blacksquaremedia.reason.classific" +
      "ation.ftrl\032%github.com/bsm/reason/core/c" +
      "ore.proto\032-github.com/gogo/protobuf/gogo" +
      "proto/gogo.proto\"n\n\tOptimizer\0222\n\005model\030\001" +
      " \001(\0132#.blacksquaremedia.reason.core.Mode" +
      "l\022\016\n\006target\030\002 \001(\t\022\014\n\004sums\030\003 \003(\001\022\017\n\007weigh" +
      "ts\030\004 \003(\001BN\n*com.blacksquaremedia.reason." +
      "classificationB\nFTRLProtosZ\010internal\310\341\036\000" +
      "\330\341\036\001\220\343\036\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.blacksquaremedia.reason.CoreProtos.getDescriptor(),
          com.google.protobuf.GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_blacksquaremedia_reason_classification_ftrl_Optimizer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_blacksquaremedia_reason_classification_ftrl_Optimizer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blacksquaremedia_reason_classification_ftrl_Optimizer_descriptor,
        new java.lang.String[] { "Model", "Target", "Sums", "Weights", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.goprotoGettersAll);
    registry.add(com.google.protobuf.GoGoProtos.goprotoStringerAll);
    registry.add(com.google.protobuf.GoGoProtos.goprotoUnrecognizedAll);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.blacksquaremedia.reason.CoreProtos.getDescriptor();
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
