// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/core.proto

package com.blacksquaremedia.reason;

public final class CoreProtos {
  private CoreProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:blacksquaremedia.reason.core.Model)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
     */
    int getFeaturesCount();
    /**
     * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
     */
    boolean containsFeatures(
        java.lang.String key);
    /**
     * Use {@link #getFeaturesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature>
    getFeatures();
    /**
     * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
     */
    java.util.Map<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature>
    getFeaturesMap();
    /**
     * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
     */

    com.blacksquaremedia.reason.CoreProtos.Feature getFeaturesOrDefault(
        java.lang.String key,
        com.blacksquaremedia.reason.CoreProtos.Feature defaultValue);
    /**
     * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
     */

    com.blacksquaremedia.reason.CoreProtos.Feature getFeaturesOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * Model describes a set of features
   * </pre>
   *
   * Protobuf type {@code blacksquaremedia.reason.core.Model}
   */
  public  static final class Model extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:blacksquaremedia.reason.core.Model)
      ModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Model.newBuilder() to construct.
    private Model(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Model() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Model(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                features_ = com.google.protobuf.MapField.newMapField(
                    FeaturesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature>
              features__ = input.readMessage(
                  FeaturesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              features_.getMutableMap().put(
                  features__.getKey(), features__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blacksquaremedia.reason.CoreProtos.internal_static_blacksquaremedia_reason_core_Model_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetFeatures();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blacksquaremedia.reason.CoreProtos.internal_static_blacksquaremedia_reason_core_Model_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blacksquaremedia.reason.CoreProtos.Model.class, com.blacksquaremedia.reason.CoreProtos.Model.Builder.class);
    }

    public static final int FEATURES_FIELD_NUMBER = 1;
    private static final class FeaturesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature>newDefaultInstance(
                  com.blacksquaremedia.reason.CoreProtos.internal_static_blacksquaremedia_reason_core_Model_FeaturesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.blacksquaremedia.reason.CoreProtos.Feature.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature> features_;
    private com.google.protobuf.MapField<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature>
    internalGetFeatures() {
      if (features_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FeaturesDefaultEntryHolder.defaultEntry);
      }
      return features_;
    }

    public int getFeaturesCount() {
      return internalGetFeatures().getMap().size();
    }
    /**
     * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
     */

    public boolean containsFeatures(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetFeatures().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFeaturesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature> getFeatures() {
      return getFeaturesMap();
    }
    /**
     * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
     */

    public java.util.Map<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature> getFeaturesMap() {
      return internalGetFeatures().getMap();
    }
    /**
     * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
     */

    public com.blacksquaremedia.reason.CoreProtos.Feature getFeaturesOrDefault(
        java.lang.String key,
        com.blacksquaremedia.reason.CoreProtos.Feature defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature> map =
          internalGetFeatures().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
     */

    public com.blacksquaremedia.reason.CoreProtos.Feature getFeaturesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature> map =
          internalGetFeatures().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetFeatures(),
          FeaturesDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature> entry
           : internalGetFeatures().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature>
        features__ = FeaturesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, features__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.blacksquaremedia.reason.CoreProtos.Model)) {
        return super.equals(obj);
      }
      com.blacksquaremedia.reason.CoreProtos.Model other = (com.blacksquaremedia.reason.CoreProtos.Model) obj;

      boolean result = true;
      result = result && internalGetFeatures().equals(
          other.internalGetFeatures());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetFeatures().getMap().isEmpty()) {
        hash = (37 * hash) + FEATURES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetFeatures().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.blacksquaremedia.reason.CoreProtos.Model parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Model parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Model parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Model parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Model parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Model parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Model parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Model parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Model parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Model parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Model parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Model parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blacksquaremedia.reason.CoreProtos.Model prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Model describes a set of features
     * </pre>
     *
     * Protobuf type {@code blacksquaremedia.reason.core.Model}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:blacksquaremedia.reason.core.Model)
        com.blacksquaremedia.reason.CoreProtos.ModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blacksquaremedia.reason.CoreProtos.internal_static_blacksquaremedia_reason_core_Model_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetFeatures();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableFeatures();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blacksquaremedia.reason.CoreProtos.internal_static_blacksquaremedia_reason_core_Model_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blacksquaremedia.reason.CoreProtos.Model.class, com.blacksquaremedia.reason.CoreProtos.Model.Builder.class);
      }

      // Construct using com.blacksquaremedia.reason.CoreProtos.Model.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableFeatures().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blacksquaremedia.reason.CoreProtos.internal_static_blacksquaremedia_reason_core_Model_descriptor;
      }

      public com.blacksquaremedia.reason.CoreProtos.Model getDefaultInstanceForType() {
        return com.blacksquaremedia.reason.CoreProtos.Model.getDefaultInstance();
      }

      public com.blacksquaremedia.reason.CoreProtos.Model build() {
        com.blacksquaremedia.reason.CoreProtos.Model result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blacksquaremedia.reason.CoreProtos.Model buildPartial() {
        com.blacksquaremedia.reason.CoreProtos.Model result = new com.blacksquaremedia.reason.CoreProtos.Model(this);
        int from_bitField0_ = bitField0_;
        result.features_ = internalGetFeatures();
        result.features_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blacksquaremedia.reason.CoreProtos.Model) {
          return mergeFrom((com.blacksquaremedia.reason.CoreProtos.Model)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blacksquaremedia.reason.CoreProtos.Model other) {
        if (other == com.blacksquaremedia.reason.CoreProtos.Model.getDefaultInstance()) return this;
        internalGetMutableFeatures().mergeFrom(
            other.internalGetFeatures());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blacksquaremedia.reason.CoreProtos.Model parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blacksquaremedia.reason.CoreProtos.Model) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature> features_;
      private com.google.protobuf.MapField<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature>
      internalGetFeatures() {
        if (features_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              FeaturesDefaultEntryHolder.defaultEntry);
        }
        return features_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature>
      internalGetMutableFeatures() {
        onChanged();;
        if (features_ == null) {
          features_ = com.google.protobuf.MapField.newMapField(
              FeaturesDefaultEntryHolder.defaultEntry);
        }
        if (!features_.isMutable()) {
          features_ = features_.copy();
        }
        return features_;
      }

      public int getFeaturesCount() {
        return internalGetFeatures().getMap().size();
      }
      /**
       * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
       */

      public boolean containsFeatures(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetFeatures().getMap().containsKey(key);
      }
      /**
       * Use {@link #getFeaturesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature> getFeatures() {
        return getFeaturesMap();
      }
      /**
       * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
       */

      public java.util.Map<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature> getFeaturesMap() {
        return internalGetFeatures().getMap();
      }
      /**
       * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
       */

      public com.blacksquaremedia.reason.CoreProtos.Feature getFeaturesOrDefault(
          java.lang.String key,
          com.blacksquaremedia.reason.CoreProtos.Feature defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature> map =
            internalGetFeatures().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
       */

      public com.blacksquaremedia.reason.CoreProtos.Feature getFeaturesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature> map =
            internalGetFeatures().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearFeatures() {
        internalGetMutableFeatures().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
       */

      public Builder removeFeatures(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableFeatures().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature>
      getMutableFeatures() {
        return internalGetMutableFeatures().getMutableMap();
      }
      /**
       * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
       */
      public Builder putFeatures(
          java.lang.String key,
          com.blacksquaremedia.reason.CoreProtos.Feature value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableFeatures().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .blacksquaremedia.reason.core.Feature&gt; features = 1;</code>
       */

      public Builder putAllFeatures(
          java.util.Map<java.lang.String, com.blacksquaremedia.reason.CoreProtos.Feature> values) {
        internalGetMutableFeatures().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:blacksquaremedia.reason.core.Model)
    }

    // @@protoc_insertion_point(class_scope:blacksquaremedia.reason.core.Model)
    private static final com.blacksquaremedia.reason.CoreProtos.Model DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blacksquaremedia.reason.CoreProtos.Model();
    }

    public static com.blacksquaremedia.reason.CoreProtos.Model getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Model>
        PARSER = new com.google.protobuf.AbstractParser<Model>() {
      public Model parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Model(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Model> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Model> getParserForType() {
      return PARSER;
    }

    public com.blacksquaremedia.reason.CoreProtos.Model getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FeatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:blacksquaremedia.reason.core.Feature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The name.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * The name.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * The kind.
     * </pre>
     *
     * <code>.blacksquaremedia.reason.core.Feature.Kind kind = 2;</code>
     */
    int getKindValue();
    /**
     * <pre>
     * The kind.
     * </pre>
     *
     * <code>.blacksquaremedia.reason.core.Feature.Kind kind = 2;</code>
     */
    com.blacksquaremedia.reason.CoreProtos.Feature.Kind getKind();

    /**
     * <pre>
     * The categorical bucketing strategy.
     * </pre>
     *
     * <code>.blacksquaremedia.reason.core.Feature.Strategy strategy = 3;</code>
     */
    int getStrategyValue();
    /**
     * <pre>
     * The categorical bucketing strategy.
     * </pre>
     *
     * <code>.blacksquaremedia.reason.core.Feature.Strategy strategy = 3;</code>
     */
    com.blacksquaremedia.reason.CoreProtos.Feature.Strategy getStrategy();

    /**
     * <pre>
     * List of known fact values.
     * </pre>
     *
     * <code>repeated string vocabulary = 4;</code>
     */
    java.util.List<java.lang.String>
        getVocabularyList();
    /**
     * <pre>
     * List of known fact values.
     * </pre>
     *
     * <code>repeated string vocabulary = 4;</code>
     */
    int getVocabularyCount();
    /**
     * <pre>
     * List of known fact values.
     * </pre>
     *
     * <code>repeated string vocabulary = 4;</code>
     */
    java.lang.String getVocabulary(int index);
    /**
     * <pre>
     * List of known fact values.
     * </pre>
     *
     * <code>repeated string vocabulary = 4;</code>
     */
    com.google.protobuf.ByteString
        getVocabularyBytes(int index);

    /**
     * <pre>
     * Defines the number of hash buckets used by hashed
     * categorical features.
     * </pre>
     *
     * <code>uint32 hash_buckets = 5;</code>
     */
    int getHashBuckets();
  }
  /**
   * <pre>
   * Feature is an attribute of a fact/example.
   * </pre>
   *
   * Protobuf type {@code blacksquaremedia.reason.core.Feature}
   */
  public  static final class Feature extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:blacksquaremedia.reason.core.Feature)
      FeatureOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Feature.newBuilder() to construct.
    private Feature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Feature() {
      name_ = "";
      kind_ = 0;
      strategy_ = 0;
      vocabulary_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      hashBuckets_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Feature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              kind_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              strategy_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                vocabulary_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              vocabulary_.add(s);
              break;
            }
            case 40: {

              hashBuckets_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          vocabulary_ = vocabulary_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blacksquaremedia.reason.CoreProtos.internal_static_blacksquaremedia_reason_core_Feature_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blacksquaremedia.reason.CoreProtos.internal_static_blacksquaremedia_reason_core_Feature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blacksquaremedia.reason.CoreProtos.Feature.class, com.blacksquaremedia.reason.CoreProtos.Feature.Builder.class);
    }

    /**
     * <pre>
     * Kind identifies the feature type.
     * </pre>
     *
     * Protobuf enum {@code blacksquaremedia.reason.core.Feature.Kind}
     */
    public enum Kind
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NUMERICAL = 0;</code>
       */
      NUMERICAL(0),
      /**
       * <code>CATEGORICAL = 1;</code>
       */
      CATEGORICAL(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NUMERICAL = 0;</code>
       */
      public static final int NUMERICAL_VALUE = 0;
      /**
       * <code>CATEGORICAL = 1;</code>
       */
      public static final int CATEGORICAL_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Kind valueOf(int value) {
        return forNumber(value);
      }

      public static Kind forNumber(int value) {
        switch (value) {
          case 0: return NUMERICAL;
          case 1: return CATEGORICAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Kind>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Kind> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Kind>() {
              public Kind findValueByNumber(int number) {
                return Kind.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.blacksquaremedia.reason.CoreProtos.Feature.getDescriptor().getEnumTypes().get(0);
      }

      private static final Kind[] VALUES = values();

      public static Kind valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Kind(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:blacksquaremedia.reason.core.Feature.Kind)
    }

    /**
     * <pre>
     * Strategies apply to categorical features and define how
     * fact value are converted to numeric category indices.
     * </pre>
     *
     * Protobuf enum {@code blacksquaremedia.reason.core.Feature.Strategy}
     */
    public enum Strategy
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * This is the default strategy where categories are calculated as
       * the index of the value in the vocabulary list. This strategy can
       * be used in combination with HashBuckets to look up values outside
       * the vocabulary.
       * </pre>
       *
       * <code>VOCABULARY = 0;</code>
       */
      VOCABULARY(0),
      /**
       * <pre>
       * Categorical feature with an identity simply use the numeric fact
       * values s the category.
       * </pre>
       *
       * <code>IDENTITY = 1;</code>
       */
      IDENTITY(1),
      /**
       * <pre>
       * Like VOCABULARY this uses a vocabulary but - instead of referring to
       * HashBuckets - unknown values are appended to the vocabulary list.
       * Please use this option with care as there is no limitation for growth.
       * </pre>
       *
       * <code>EXPANDABLE = 2;</code>
       */
      EXPANDABLE(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * This is the default strategy where categories are calculated as
       * the index of the value in the vocabulary list. This strategy can
       * be used in combination with HashBuckets to look up values outside
       * the vocabulary.
       * </pre>
       *
       * <code>VOCABULARY = 0;</code>
       */
      public static final int VOCABULARY_VALUE = 0;
      /**
       * <pre>
       * Categorical feature with an identity simply use the numeric fact
       * values s the category.
       * </pre>
       *
       * <code>IDENTITY = 1;</code>
       */
      public static final int IDENTITY_VALUE = 1;
      /**
       * <pre>
       * Like VOCABULARY this uses a vocabulary but - instead of referring to
       * HashBuckets - unknown values are appended to the vocabulary list.
       * Please use this option with care as there is no limitation for growth.
       * </pre>
       *
       * <code>EXPANDABLE = 2;</code>
       */
      public static final int EXPANDABLE_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Strategy valueOf(int value) {
        return forNumber(value);
      }

      public static Strategy forNumber(int value) {
        switch (value) {
          case 0: return VOCABULARY;
          case 1: return IDENTITY;
          case 2: return EXPANDABLE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Strategy>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Strategy> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Strategy>() {
              public Strategy findValueByNumber(int number) {
                return Strategy.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.blacksquaremedia.reason.CoreProtos.Feature.getDescriptor().getEnumTypes().get(1);
      }

      private static final Strategy[] VALUES = values();

      public static Strategy valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Strategy(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:blacksquaremedia.reason.core.Feature.Strategy)
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * The name.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The name.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KIND_FIELD_NUMBER = 2;
    private int kind_;
    /**
     * <pre>
     * The kind.
     * </pre>
     *
     * <code>.blacksquaremedia.reason.core.Feature.Kind kind = 2;</code>
     */
    public int getKindValue() {
      return kind_;
    }
    /**
     * <pre>
     * The kind.
     * </pre>
     *
     * <code>.blacksquaremedia.reason.core.Feature.Kind kind = 2;</code>
     */
    public com.blacksquaremedia.reason.CoreProtos.Feature.Kind getKind() {
      com.blacksquaremedia.reason.CoreProtos.Feature.Kind result = com.blacksquaremedia.reason.CoreProtos.Feature.Kind.valueOf(kind_);
      return result == null ? com.blacksquaremedia.reason.CoreProtos.Feature.Kind.UNRECOGNIZED : result;
    }

    public static final int STRATEGY_FIELD_NUMBER = 3;
    private int strategy_;
    /**
     * <pre>
     * The categorical bucketing strategy.
     * </pre>
     *
     * <code>.blacksquaremedia.reason.core.Feature.Strategy strategy = 3;</code>
     */
    public int getStrategyValue() {
      return strategy_;
    }
    /**
     * <pre>
     * The categorical bucketing strategy.
     * </pre>
     *
     * <code>.blacksquaremedia.reason.core.Feature.Strategy strategy = 3;</code>
     */
    public com.blacksquaremedia.reason.CoreProtos.Feature.Strategy getStrategy() {
      com.blacksquaremedia.reason.CoreProtos.Feature.Strategy result = com.blacksquaremedia.reason.CoreProtos.Feature.Strategy.valueOf(strategy_);
      return result == null ? com.blacksquaremedia.reason.CoreProtos.Feature.Strategy.UNRECOGNIZED : result;
    }

    public static final int VOCABULARY_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList vocabulary_;
    /**
     * <pre>
     * List of known fact values.
     * </pre>
     *
     * <code>repeated string vocabulary = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getVocabularyList() {
      return vocabulary_;
    }
    /**
     * <pre>
     * List of known fact values.
     * </pre>
     *
     * <code>repeated string vocabulary = 4;</code>
     */
    public int getVocabularyCount() {
      return vocabulary_.size();
    }
    /**
     * <pre>
     * List of known fact values.
     * </pre>
     *
     * <code>repeated string vocabulary = 4;</code>
     */
    public java.lang.String getVocabulary(int index) {
      return vocabulary_.get(index);
    }
    /**
     * <pre>
     * List of known fact values.
     * </pre>
     *
     * <code>repeated string vocabulary = 4;</code>
     */
    public com.google.protobuf.ByteString
        getVocabularyBytes(int index) {
      return vocabulary_.getByteString(index);
    }

    public static final int HASH_BUCKETS_FIELD_NUMBER = 5;
    private int hashBuckets_;
    /**
     * <pre>
     * Defines the number of hash buckets used by hashed
     * categorical features.
     * </pre>
     *
     * <code>uint32 hash_buckets = 5;</code>
     */
    public int getHashBuckets() {
      return hashBuckets_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (kind_ != com.blacksquaremedia.reason.CoreProtos.Feature.Kind.NUMERICAL.getNumber()) {
        output.writeEnum(2, kind_);
      }
      if (strategy_ != com.blacksquaremedia.reason.CoreProtos.Feature.Strategy.VOCABULARY.getNumber()) {
        output.writeEnum(3, strategy_);
      }
      for (int i = 0; i < vocabulary_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, vocabulary_.getRaw(i));
      }
      if (hashBuckets_ != 0) {
        output.writeUInt32(5, hashBuckets_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (kind_ != com.blacksquaremedia.reason.CoreProtos.Feature.Kind.NUMERICAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, kind_);
      }
      if (strategy_ != com.blacksquaremedia.reason.CoreProtos.Feature.Strategy.VOCABULARY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, strategy_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < vocabulary_.size(); i++) {
          dataSize += computeStringSizeNoTag(vocabulary_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getVocabularyList().size();
      }
      if (hashBuckets_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, hashBuckets_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.blacksquaremedia.reason.CoreProtos.Feature)) {
        return super.equals(obj);
      }
      com.blacksquaremedia.reason.CoreProtos.Feature other = (com.blacksquaremedia.reason.CoreProtos.Feature) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && kind_ == other.kind_;
      result = result && strategy_ == other.strategy_;
      result = result && getVocabularyList()
          .equals(other.getVocabularyList());
      result = result && (getHashBuckets()
          == other.getHashBuckets());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + KIND_FIELD_NUMBER;
      hash = (53 * hash) + kind_;
      hash = (37 * hash) + STRATEGY_FIELD_NUMBER;
      hash = (53 * hash) + strategy_;
      if (getVocabularyCount() > 0) {
        hash = (37 * hash) + VOCABULARY_FIELD_NUMBER;
        hash = (53 * hash) + getVocabularyList().hashCode();
      }
      hash = (37 * hash) + HASH_BUCKETS_FIELD_NUMBER;
      hash = (53 * hash) + getHashBuckets();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.blacksquaremedia.reason.CoreProtos.Feature parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Feature parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Feature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Feature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Feature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Feature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Feature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Feature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Feature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Feature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Feature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blacksquaremedia.reason.CoreProtos.Feature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blacksquaremedia.reason.CoreProtos.Feature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Feature is an attribute of a fact/example.
     * </pre>
     *
     * Protobuf type {@code blacksquaremedia.reason.core.Feature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:blacksquaremedia.reason.core.Feature)
        com.blacksquaremedia.reason.CoreProtos.FeatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blacksquaremedia.reason.CoreProtos.internal_static_blacksquaremedia_reason_core_Feature_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blacksquaremedia.reason.CoreProtos.internal_static_blacksquaremedia_reason_core_Feature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blacksquaremedia.reason.CoreProtos.Feature.class, com.blacksquaremedia.reason.CoreProtos.Feature.Builder.class);
      }

      // Construct using com.blacksquaremedia.reason.CoreProtos.Feature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        kind_ = 0;

        strategy_ = 0;

        vocabulary_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        hashBuckets_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blacksquaremedia.reason.CoreProtos.internal_static_blacksquaremedia_reason_core_Feature_descriptor;
      }

      public com.blacksquaremedia.reason.CoreProtos.Feature getDefaultInstanceForType() {
        return com.blacksquaremedia.reason.CoreProtos.Feature.getDefaultInstance();
      }

      public com.blacksquaremedia.reason.CoreProtos.Feature build() {
        com.blacksquaremedia.reason.CoreProtos.Feature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blacksquaremedia.reason.CoreProtos.Feature buildPartial() {
        com.blacksquaremedia.reason.CoreProtos.Feature result = new com.blacksquaremedia.reason.CoreProtos.Feature(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.kind_ = kind_;
        result.strategy_ = strategy_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          vocabulary_ = vocabulary_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.vocabulary_ = vocabulary_;
        result.hashBuckets_ = hashBuckets_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blacksquaremedia.reason.CoreProtos.Feature) {
          return mergeFrom((com.blacksquaremedia.reason.CoreProtos.Feature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blacksquaremedia.reason.CoreProtos.Feature other) {
        if (other == com.blacksquaremedia.reason.CoreProtos.Feature.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.kind_ != 0) {
          setKindValue(other.getKindValue());
        }
        if (other.strategy_ != 0) {
          setStrategyValue(other.getStrategyValue());
        }
        if (!other.vocabulary_.isEmpty()) {
          if (vocabulary_.isEmpty()) {
            vocabulary_ = other.vocabulary_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureVocabularyIsMutable();
            vocabulary_.addAll(other.vocabulary_);
          }
          onChanged();
        }
        if (other.getHashBuckets() != 0) {
          setHashBuckets(other.getHashBuckets());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blacksquaremedia.reason.CoreProtos.Feature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blacksquaremedia.reason.CoreProtos.Feature) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * The name.
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The name.
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The name.
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The name.
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The name.
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int kind_ = 0;
      /**
       * <pre>
       * The kind.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Feature.Kind kind = 2;</code>
       */
      public int getKindValue() {
        return kind_;
      }
      /**
       * <pre>
       * The kind.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Feature.Kind kind = 2;</code>
       */
      public Builder setKindValue(int value) {
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The kind.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Feature.Kind kind = 2;</code>
       */
      public com.blacksquaremedia.reason.CoreProtos.Feature.Kind getKind() {
        com.blacksquaremedia.reason.CoreProtos.Feature.Kind result = com.blacksquaremedia.reason.CoreProtos.Feature.Kind.valueOf(kind_);
        return result == null ? com.blacksquaremedia.reason.CoreProtos.Feature.Kind.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * The kind.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Feature.Kind kind = 2;</code>
       */
      public Builder setKind(com.blacksquaremedia.reason.CoreProtos.Feature.Kind value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        kind_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The kind.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Feature.Kind kind = 2;</code>
       */
      public Builder clearKind() {
        
        kind_ = 0;
        onChanged();
        return this;
      }

      private int strategy_ = 0;
      /**
       * <pre>
       * The categorical bucketing strategy.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Feature.Strategy strategy = 3;</code>
       */
      public int getStrategyValue() {
        return strategy_;
      }
      /**
       * <pre>
       * The categorical bucketing strategy.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Feature.Strategy strategy = 3;</code>
       */
      public Builder setStrategyValue(int value) {
        strategy_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The categorical bucketing strategy.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Feature.Strategy strategy = 3;</code>
       */
      public com.blacksquaremedia.reason.CoreProtos.Feature.Strategy getStrategy() {
        com.blacksquaremedia.reason.CoreProtos.Feature.Strategy result = com.blacksquaremedia.reason.CoreProtos.Feature.Strategy.valueOf(strategy_);
        return result == null ? com.blacksquaremedia.reason.CoreProtos.Feature.Strategy.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * The categorical bucketing strategy.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Feature.Strategy strategy = 3;</code>
       */
      public Builder setStrategy(com.blacksquaremedia.reason.CoreProtos.Feature.Strategy value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        strategy_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The categorical bucketing strategy.
       * </pre>
       *
       * <code>.blacksquaremedia.reason.core.Feature.Strategy strategy = 3;</code>
       */
      public Builder clearStrategy() {
        
        strategy_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList vocabulary_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureVocabularyIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          vocabulary_ = new com.google.protobuf.LazyStringArrayList(vocabulary_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <pre>
       * List of known fact values.
       * </pre>
       *
       * <code>repeated string vocabulary = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getVocabularyList() {
        return vocabulary_.getUnmodifiableView();
      }
      /**
       * <pre>
       * List of known fact values.
       * </pre>
       *
       * <code>repeated string vocabulary = 4;</code>
       */
      public int getVocabularyCount() {
        return vocabulary_.size();
      }
      /**
       * <pre>
       * List of known fact values.
       * </pre>
       *
       * <code>repeated string vocabulary = 4;</code>
       */
      public java.lang.String getVocabulary(int index) {
        return vocabulary_.get(index);
      }
      /**
       * <pre>
       * List of known fact values.
       * </pre>
       *
       * <code>repeated string vocabulary = 4;</code>
       */
      public com.google.protobuf.ByteString
          getVocabularyBytes(int index) {
        return vocabulary_.getByteString(index);
      }
      /**
       * <pre>
       * List of known fact values.
       * </pre>
       *
       * <code>repeated string vocabulary = 4;</code>
       */
      public Builder setVocabulary(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVocabularyIsMutable();
        vocabulary_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of known fact values.
       * </pre>
       *
       * <code>repeated string vocabulary = 4;</code>
       */
      public Builder addVocabulary(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVocabularyIsMutable();
        vocabulary_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of known fact values.
       * </pre>
       *
       * <code>repeated string vocabulary = 4;</code>
       */
      public Builder addAllVocabulary(
          java.lang.Iterable<java.lang.String> values) {
        ensureVocabularyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vocabulary_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of known fact values.
       * </pre>
       *
       * <code>repeated string vocabulary = 4;</code>
       */
      public Builder clearVocabulary() {
        vocabulary_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of known fact values.
       * </pre>
       *
       * <code>repeated string vocabulary = 4;</code>
       */
      public Builder addVocabularyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureVocabularyIsMutable();
        vocabulary_.add(value);
        onChanged();
        return this;
      }

      private int hashBuckets_ ;
      /**
       * <pre>
       * Defines the number of hash buckets used by hashed
       * categorical features.
       * </pre>
       *
       * <code>uint32 hash_buckets = 5;</code>
       */
      public int getHashBuckets() {
        return hashBuckets_;
      }
      /**
       * <pre>
       * Defines the number of hash buckets used by hashed
       * categorical features.
       * </pre>
       *
       * <code>uint32 hash_buckets = 5;</code>
       */
      public Builder setHashBuckets(int value) {
        
        hashBuckets_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Defines the number of hash buckets used by hashed
       * categorical features.
       * </pre>
       *
       * <code>uint32 hash_buckets = 5;</code>
       */
      public Builder clearHashBuckets() {
        
        hashBuckets_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:blacksquaremedia.reason.core.Feature)
    }

    // @@protoc_insertion_point(class_scope:blacksquaremedia.reason.core.Feature)
    private static final com.blacksquaremedia.reason.CoreProtos.Feature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blacksquaremedia.reason.CoreProtos.Feature();
    }

    public static com.blacksquaremedia.reason.CoreProtos.Feature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Feature>
        PARSER = new com.google.protobuf.AbstractParser<Feature>() {
      public Feature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Feature(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Feature> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Feature> getParserForType() {
      return PARSER;
    }

    public com.blacksquaremedia.reason.CoreProtos.Feature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blacksquaremedia_reason_core_Model_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blacksquaremedia_reason_core_Model_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blacksquaremedia_reason_core_Model_FeaturesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blacksquaremedia_reason_core_Model_FeaturesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blacksquaremedia_reason_core_Feature_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blacksquaremedia_reason_core_Feature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017core/core.proto\022\034blacksquaremedia.reas" +
      "on.core\032-github.com/gogo/protobuf/gogopr" +
      "oto/gogo.proto\"\244\001\n\005Model\022C\n\010features\030\001 \003" +
      "(\01321.blacksquaremedia.reason.core.Model." +
      "FeaturesEntry\032V\n\rFeaturesEntry\022\013\n\003key\030\001 " +
      "\001(\t\0224\n\005value\030\002 \001(\0132%.blacksquaremedia.re" +
      "ason.core.Feature:\0028\001\"\237\002\n\007Feature\022\014\n\004nam" +
      "e\030\001 \001(\t\0228\n\004kind\030\002 \001(\0162*.blacksquaremedia" +
      ".reason.core.Feature.Kind\022@\n\010strategy\030\003 " +
      "\001(\0162..blacksquaremedia.reason.core.Featu" +
      "re.Strategy\022\022\n\nvocabulary\030\004 \003(\t\022\024\n\014hash_" +
      "buckets\030\005 \001(\r\"&\n\004Kind\022\r\n\tNUMERICAL\020\000\022\017\n\013" +
      "CATEGORICAL\020\001\"8\n\010Strategy\022\016\n\nVOCABULARY\020" +
      "\000\022\014\n\010IDENTITY\020\001\022\016\n\nEXPANDABLE\020\002B;\n\033com.b" +
      "lacksquaremedia.reasonB\nCoreProtosZ\004core" +
      "\310\341\036\000\330\341\036\001\220\343\036\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_blacksquaremedia_reason_core_Model_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_blacksquaremedia_reason_core_Model_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blacksquaremedia_reason_core_Model_descriptor,
        new java.lang.String[] { "Features", });
    internal_static_blacksquaremedia_reason_core_Model_FeaturesEntry_descriptor =
      internal_static_blacksquaremedia_reason_core_Model_descriptor.getNestedTypes().get(0);
    internal_static_blacksquaremedia_reason_core_Model_FeaturesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blacksquaremedia_reason_core_Model_FeaturesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_blacksquaremedia_reason_core_Feature_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_blacksquaremedia_reason_core_Feature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blacksquaremedia_reason_core_Feature_descriptor,
        new java.lang.String[] { "Name", "Kind", "Strategy", "Vocabulary", "HashBuckets", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.goprotoGettersAll);
    registry.add(com.google.protobuf.GoGoProtos.goprotoStringerAll);
    registry.add(com.google.protobuf.GoGoProtos.goprotoUnrecognizedAll);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
