// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: regression/hoeffding/internal/internal.proto

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	regression/hoeffding/internal/internal.proto

It has these top-level messages:
	Tree
	FeatureStats
	Node
	SplitNode
	LeafNode
*/
package internal

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import blacksquaremedia_reason_core "github.com/bsm/reason/core"
import blacksquaremedia_reason_util "github.com/bsm/reason/util"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Tree wraps the tree data.
type Tree struct {
	// The underlying model.
	Model *blacksquaremedia_reason_core.Model `protobuf:"bytes,1,opt,name=model" json:"model,omitempty"`
	// The target feature.
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// The root nodeRef.
	Root int64 `protobuf:"varint,3,opt,name=root,proto3" json:"root,omitempty"`
	// The node registry.
	Nodes []*Node `protobuf:"bytes,4,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *Tree) Reset()                    { *m = Tree{} }
func (m *Tree) String() string            { return proto.CompactTextString(m) }
func (*Tree) ProtoMessage()               {}
func (*Tree) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{0} }

// FeatureStats instances maintain stats based on
// observation of a particular feature.
type FeatureStats struct {
	// Types that are valid to be assigned to Kind:
	//	*FeatureStats_Numerical_
	//	*FeatureStats_Categorical_
	Kind isFeatureStats_Kind `protobuf_oneof:"kind"`
}

func (m *FeatureStats) Reset()                    { *m = FeatureStats{} }
func (m *FeatureStats) String() string            { return proto.CompactTextString(m) }
func (*FeatureStats) ProtoMessage()               {}
func (*FeatureStats) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{1} }

type isFeatureStats_Kind interface {
	isFeatureStats_Kind()
}

type FeatureStats_Numerical_ struct {
	Numerical *FeatureStats_Numerical `protobuf:"bytes,1,opt,name=numerical,oneof"`
}
type FeatureStats_Categorical_ struct {
	Categorical *FeatureStats_Categorical `protobuf:"bytes,2,opt,name=categorical,oneof"`
}

func (*FeatureStats_Numerical_) isFeatureStats_Kind()   {}
func (*FeatureStats_Categorical_) isFeatureStats_Kind() {}

func (m *FeatureStats) GetKind() isFeatureStats_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *FeatureStats) GetNumerical() *FeatureStats_Numerical {
	if x, ok := m.GetKind().(*FeatureStats_Numerical_); ok {
		return x.Numerical
	}
	return nil
}

func (m *FeatureStats) GetCategorical() *FeatureStats_Categorical {
	if x, ok := m.GetKind().(*FeatureStats_Categorical_); ok {
		return x.Categorical
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FeatureStats) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FeatureStats_OneofMarshaler, _FeatureStats_OneofUnmarshaler, _FeatureStats_OneofSizer, []interface{}{
		(*FeatureStats_Numerical_)(nil),
		(*FeatureStats_Categorical_)(nil),
	}
}

func _FeatureStats_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FeatureStats)
	// kind
	switch x := m.Kind.(type) {
	case *FeatureStats_Numerical_:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Numerical); err != nil {
			return err
		}
	case *FeatureStats_Categorical_:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Categorical); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("FeatureStats.Kind has unexpected type %T", x)
	}
	return nil
}

func _FeatureStats_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FeatureStats)
	switch tag {
	case 1: // kind.numerical
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FeatureStats_Numerical)
		err := b.DecodeMessage(msg)
		m.Kind = &FeatureStats_Numerical_{msg}
		return true, err
	case 2: // kind.categorical
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FeatureStats_Categorical)
		err := b.DecodeMessage(msg)
		m.Kind = &FeatureStats_Categorical_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _FeatureStats_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FeatureStats)
	// kind
	switch x := m.Kind.(type) {
	case *FeatureStats_Numerical_:
		s := proto.Size(x.Numerical)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *FeatureStats_Categorical_:
		s := proto.Size(x.Categorical)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type FeatureStats_Numerical struct {
	Min          float64                              `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max          float64                              `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	Observations []FeatureStats_Numerical_Observation `protobuf:"bytes,3,rep,name=observations" json:"observations"`
}

func (m *FeatureStats_Numerical) Reset()         { *m = FeatureStats_Numerical{} }
func (m *FeatureStats_Numerical) String() string { return proto.CompactTextString(m) }
func (*FeatureStats_Numerical) ProtoMessage()    {}
func (*FeatureStats_Numerical) Descriptor() ([]byte, []int) {
	return fileDescriptorInternal, []int{1, 0}
}

type FeatureStats_Numerical_Observation struct {
	FeatureValue float64 `protobuf:"fixed64,1,opt,name=feature_value,json=featureValue,proto3" json:"feature_value,omitempty"`
	TargetValue  float64 `protobuf:"fixed64,2,opt,name=target_value,json=targetValue,proto3" json:"target_value,omitempty"`
	Weight       float64 `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (m *FeatureStats_Numerical_Observation) Reset()         { *m = FeatureStats_Numerical_Observation{} }
func (m *FeatureStats_Numerical_Observation) String() string { return proto.CompactTextString(m) }
func (*FeatureStats_Numerical_Observation) ProtoMessage()    {}
func (*FeatureStats_Numerical_Observation) Descriptor() ([]byte, []int) {
	return fileDescriptorInternal, []int{1, 0, 0}
}

type FeatureStats_Categorical struct {
	blacksquaremedia_reason_util.StreamStatsDistribution `protobuf:"bytes,1,opt,name=stats,embedded=stats" json:"stats"`
}

func (m *FeatureStats_Categorical) Reset()         { *m = FeatureStats_Categorical{} }
func (m *FeatureStats_Categorical) String() string { return proto.CompactTextString(m) }
func (*FeatureStats_Categorical) ProtoMessage()    {}
func (*FeatureStats_Categorical) Descriptor() ([]byte, []int) {
	return fileDescriptorInternal, []int{1, 1}
}

// Node is a tree node
type Node struct {
	// Observation stats for the node
	Stats *blacksquaremedia_reason_util.StreamStats `protobuf:"bytes,1,opt,name=stats" json:"stats,omitempty"`
	// Nodes can be leaf or split nodes.
	//
	// Types that are valid to be assigned to Kind:
	//	*Node_Leaf
	//	*Node_Split
	Kind isNode_Kind `protobuf_oneof:"kind"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{2} }

type isNode_Kind interface {
	isNode_Kind()
}

type Node_Leaf struct {
	Leaf *LeafNode `protobuf:"bytes,2,opt,name=leaf,oneof"`
}
type Node_Split struct {
	Split *SplitNode `protobuf:"bytes,3,opt,name=split,oneof"`
}

func (*Node_Leaf) isNode_Kind()  {}
func (*Node_Split) isNode_Kind() {}

func (m *Node) GetKind() isNode_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *Node) GetLeaf() *LeafNode {
	if x, ok := m.GetKind().(*Node_Leaf); ok {
		return x.Leaf
	}
	return nil
}

func (m *Node) GetSplit() *SplitNode {
	if x, ok := m.GetKind().(*Node_Split); ok {
		return x.Split
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Node) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Node_OneofMarshaler, _Node_OneofUnmarshaler, _Node_OneofSizer, []interface{}{
		(*Node_Leaf)(nil),
		(*Node_Split)(nil),
	}
}

func _Node_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Node)
	// kind
	switch x := m.Kind.(type) {
	case *Node_Leaf:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Leaf); err != nil {
			return err
		}
	case *Node_Split:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Split); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Node.Kind has unexpected type %T", x)
	}
	return nil
}

func _Node_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Node)
	switch tag {
	case 2: // kind.leaf
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LeafNode)
		err := b.DecodeMessage(msg)
		m.Kind = &Node_Leaf{msg}
		return true, err
	case 3: // kind.split
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SplitNode)
		err := b.DecodeMessage(msg)
		m.Kind = &Node_Split{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Node_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Node)
	// kind
	switch x := m.Kind.(type) {
	case *Node_Leaf:
		s := proto.Size(x.Leaf)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Node_Split:
		s := proto.Size(x.Split)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// SplitNode instances are intermediate nodes within the tree.
type SplitNode struct {
	// The feature name (predictor).
	Feature string `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	// The pivot value for binary splits (numerical predictors).
	Pivot float64 `protobuf:"fixed64,2,opt,name=pivot,proto3" json:"pivot,omitempty"`
	// The child references.
	Children SplitNode_Children `protobuf:"bytes,3,opt,name=children" json:"children"`
}

func (m *SplitNode) Reset()                    { *m = SplitNode{} }
func (m *SplitNode) String() string            { return proto.CompactTextString(m) }
func (*SplitNode) ProtoMessage()               {}
func (*SplitNode) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{3} }

// Children is a collection of child node references.
type SplitNode_Children struct {
	Dense     []int64         `protobuf:"varint,1,rep,packed,name=dense" json:"dense,omitempty"`
	Sparse    map[int64]int64 `protobuf:"bytes,2,rep,name=sparse" json:"sparse,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	SparseCap int64           `protobuf:"varint,3,opt,name=sparse_cap,json=sparseCap,proto3" json:"sparse_cap,omitempty"`
}

func (m *SplitNode_Children) Reset()                    { *m = SplitNode_Children{} }
func (m *SplitNode_Children) String() string            { return proto.CompactTextString(m) }
func (*SplitNode_Children) ProtoMessage()               {}
func (*SplitNode_Children) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{3, 0} }

// LeafNode instances are the leaves within the tree.
type LeafNode struct {
	// Observation stats, but feature.
	FeatureStats map[string]*FeatureStats `protobuf:"bytes,1,rep,name=feature_stats,json=featureStats" json:"feature_stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	// Weight at the time of the last split evaluation.
	WeightAtLastEval float64 `protobuf:"fixed64,2,opt,name=weight_at_last_eval,json=weightAtLastEval,proto3" json:"weight_at_last_eval,omitempty"`
	// Status indicator.
	IsDisabled bool `protobuf:"varint,3,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`
}

func (m *LeafNode) Reset()                    { *m = LeafNode{} }
func (m *LeafNode) String() string            { return proto.CompactTextString(m) }
func (*LeafNode) ProtoMessage()               {}
func (*LeafNode) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{4} }

func init() {
	proto.RegisterType((*Tree)(nil), "blacksquaremedia.reason.regression.hoeffding.Tree")
	proto.RegisterType((*FeatureStats)(nil), "blacksquaremedia.reason.regression.hoeffding.FeatureStats")
	proto.RegisterType((*FeatureStats_Numerical)(nil), "blacksquaremedia.reason.regression.hoeffding.FeatureStats.Numerical")
	proto.RegisterType((*FeatureStats_Numerical_Observation)(nil), "blacksquaremedia.reason.regression.hoeffding.FeatureStats.Numerical.Observation")
	proto.RegisterType((*FeatureStats_Categorical)(nil), "blacksquaremedia.reason.regression.hoeffding.FeatureStats.Categorical")
	proto.RegisterType((*Node)(nil), "blacksquaremedia.reason.regression.hoeffding.Node")
	proto.RegisterType((*SplitNode)(nil), "blacksquaremedia.reason.regression.hoeffding.SplitNode")
	proto.RegisterType((*SplitNode_Children)(nil), "blacksquaremedia.reason.regression.hoeffding.SplitNode.Children")
	proto.RegisterType((*LeafNode)(nil), "blacksquaremedia.reason.regression.hoeffding.LeafNode")
}

func init() {
	proto.RegisterFile("regression/hoeffding/internal/internal.proto", fileDescriptorInternal)
}

var fileDescriptorInternal = []byte{
	// 820 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x4f, 0x8f, 0xdb, 0x44,
	0x14, 0xc0, 0xe3, 0xd8, 0x09, 0xc9, 0xf3, 0x22, 0xca, 0x80, 0xaa, 0x28, 0x12, 0xbb, 0xcb, 0x56,
	0xa0, 0x20, 0xb5, 0x8e, 0x14, 0xc4, 0x9f, 0xf6, 0x02, 0xec, 0xb6, 0x55, 0x0e, 0x4b, 0x77, 0x35,
	0x01, 0x0e, 0x5c, 0xa2, 0xb1, 0x3d, 0x71, 0x86, 0xb5, 0x3d, 0x61, 0x66, 0x1c, 0x5a, 0xb8, 0xf1,
	0x09, 0x38, 0xf3, 0x45, 0xf8, 0x06, 0xa8, 0x47, 0x8e, 0x9c, 0x2a, 0x2a, 0x8e, 0x48, 0x7c, 0x06,
	0x34, 0x7f, 0x9c, 0x78, 0x85, 0x56, 0x6a, 0xb6, 0xbd, 0x58, 0xef, 0x3d, 0x3f, 0xff, 0xde, 0x9f,
	0x79, 0x6f, 0x0c, 0xb7, 0x05, 0xcd, 0x04, 0x95, 0x92, 0xf1, 0x72, 0xbc, 0xe4, 0x74, 0xb1, 0x48,
	0x59, 0x99, 0x8d, 0x59, 0xa9, 0xa8, 0x28, 0x49, 0xbe, 0x11, 0xa2, 0x95, 0xe0, 0x8a, 0xa3, 0xdb,
	0x71, 0x4e, 0x92, 0x0b, 0xf9, 0x7d, 0x45, 0x04, 0x2d, 0x68, 0xca, 0x48, 0x24, 0x28, 0x91, 0xbc,
	0x8c, 0xb6, 0x94, 0x68, 0x43, 0x19, 0xbe, 0x97, 0x31, 0xb5, 0xac, 0xe2, 0x28, 0xe1, 0xc5, 0x38,
	0x96, 0xc5, 0xd8, 0xfa, 0x8e, 0x13, 0x2e, 0xa8, 0x79, 0x58, 0xe8, 0x55, 0x6e, 0x95, 0x62, 0xb9,
	0x79, 0x38, 0xb7, 0x3b, 0x0d, 0xb7, 0x8c, 0x67, 0x7c, 0x6c, 0xcc, 0x71, 0xb5, 0x30, 0x9a, 0x51,
	0x8c, 0x64, 0xdd, 0x8f, 0x7e, 0xf3, 0x20, 0xf8, 0x4a, 0x50, 0x8a, 0xee, 0x42, 0xa7, 0xe0, 0x29,
	0xcd, 0x07, 0xde, 0xa1, 0x37, 0x0a, 0x27, 0xb7, 0xa2, 0xab, 0x6a, 0x30, 0x29, 0x7d, 0xa9, 0x5d,
	0xb1, 0xfd, 0x02, 0xdd, 0x84, 0xae, 0x22, 0x22, 0xa3, 0x6a, 0xd0, 0x3e, 0xf4, 0x46, 0x7d, 0xec,
	0x34, 0x84, 0x20, 0x10, 0x9c, 0xab, 0x81, 0x7f, 0xe8, 0x8d, 0x7c, 0x6c, 0x64, 0x34, 0x85, 0x4e,
	0xc9, 0x53, 0x2a, 0x07, 0xc1, 0xa1, 0x3f, 0x0a, 0x27, 0x93, 0x68, 0x97, 0x56, 0x45, 0x8f, 0x78,
	0x4a, 0xb1, 0x05, 0x1c, 0xfd, 0x13, 0xc0, 0xde, 0x43, 0x4a, 0x54, 0x25, 0xe8, 0x4c, 0x11, 0x25,
	0x51, 0x0a, 0xfd, 0xb2, 0x2a, 0xa8, 0x60, 0x09, 0xa9, 0xab, 0xb8, 0xbf, 0x1b, 0xbe, 0x89, 0x8b,
	0x1e, 0xd5, 0xac, 0x69, 0x0b, 0x6f, 0xc1, 0xe8, 0x3b, 0x08, 0x13, 0xa2, 0x68, 0xc6, 0x6d, 0x9c,
	0xb6, 0x89, 0xf3, 0xf0, 0x25, 0xe2, 0x9c, 0x6c, 0x69, 0xd3, 0x16, 0x6e, 0xc2, 0x87, 0xbf, 0xb6,
	0xa1, 0xbf, 0x49, 0x03, 0xdd, 0x00, 0xbf, 0x60, 0xa5, 0xa9, 0xcc, 0xc3, 0x5a, 0x34, 0x16, 0xf2,
	0xd8, 0xe4, 0xa0, 0x2d, 0xe4, 0x31, 0xfa, 0x11, 0xf6, 0x78, 0x2c, 0xa9, 0x58, 0x13, 0xc5, 0x78,
	0x29, 0x07, 0xbe, 0xe9, 0xf2, 0xf9, 0xab, 0x68, 0x43, 0x74, 0xb6, 0x05, 0x1f, 0x07, 0x4f, 0x9f,
	0x1d, 0xb4, 0xf0, 0xa5, 0x58, 0xc3, 0x02, 0xc2, 0x86, 0x0b, 0xba, 0x05, 0xaf, 0x2f, 0x2c, 0x68,
	0xbe, 0x26, 0x79, 0x45, 0x5d, 0xe2, 0x7b, 0xce, 0xf8, 0x8d, 0xb6, 0xa1, 0x77, 0x61, 0xcf, 0x0e,
	0x8b, 0xf3, 0xb1, 0xa5, 0x84, 0xd6, 0x66, 0x5d, 0x6e, 0x42, 0xf7, 0x07, 0xca, 0xb2, 0xa5, 0x9d,
	0x23, 0x0f, 0x3b, 0x6d, 0x98, 0x42, 0xd8, 0x68, 0x1d, 0xfa, 0x1a, 0x3a, 0x52, 0x27, 0xec, 0x4e,
	0xfe, 0xa3, 0x2b, 0x4b, 0x36, 0xbb, 0x32, 0x53, 0x82, 0x92, 0xc2, 0x54, 0x78, 0x9f, 0x49, 0x25,
	0x58, 0x5c, 0x99, 0xba, 0x7a, 0xba, 0xae, 0x3f, 0x9e, 0x1d, 0x78, 0xd8, 0xd2, 0x8e, 0xbb, 0x10,
	0x5c, 0xb0, 0x32, 0x3d, 0xfa, 0xd7, 0x83, 0x40, 0x4f, 0x1f, 0xfa, 0xec, 0x72, 0x9c, 0x0f, 0x5e,
	0x38, 0x8e, 0x23, 0xa2, 0x53, 0x08, 0x72, 0x4a, 0x16, 0x6e, 0x72, 0x3e, 0xde, 0xed, 0x68, 0x4e,
	0x29, 0x59, 0xe8, 0x34, 0xa6, 0x2d, 0x6c, 0x28, 0xe8, 0x0c, 0x3a, 0x72, 0x95, 0x33, 0xdb, 0x9c,
	0x70, 0xf2, 0xc9, 0x6e, 0xb8, 0x99, 0xfe, 0xd4, 0xf1, 0x2c, 0x67, 0x53, 0xf0, 0xcf, 0x3e, 0xf4,
	0x37, 0xaf, 0xd1, 0x00, 0x5e, 0x73, 0xe7, 0x66, 0xea, 0xee, 0xe3, 0x5a, 0x45, 0x6f, 0x43, 0x67,
	0xc5, 0xd6, 0x5c, 0xb9, 0xa3, 0xb3, 0x0a, 0x8a, 0xa1, 0x97, 0x2c, 0x59, 0x9e, 0x0a, 0x5a, 0xba,
	0xcc, 0x3e, 0xbf, 0x66, 0x66, 0xd1, 0x89, 0xe3, 0xb8, 0x99, 0xdb, 0x70, 0x87, 0x7f, 0x79, 0xd0,
	0xab, 0x5f, 0xea, 0x34, 0x52, 0x5a, 0x4a, 0x9d, 0x9e, 0x3f, 0xf2, 0xb1, 0x55, 0x50, 0x0a, 0x5d,
	0xb9, 0x22, 0x42, 0xea, 0xc1, 0xd2, 0x8b, 0x70, 0xfa, 0xb2, 0x49, 0x44, 0x33, 0x83, 0x7b, 0x50,
	0x2a, 0xf1, 0x04, 0x3b, 0x36, 0x7a, 0x07, 0xc0, 0x4a, 0xf3, 0x84, 0xac, 0xdc, 0x6d, 0xd7, 0xb7,
	0x96, 0x13, 0xb2, 0x1a, 0xde, 0x85, 0xb0, 0xf1, 0x95, 0x5e, 0xda, 0x0b, 0xfa, 0xc4, 0xb4, 0xd1,
	0xc7, 0x5a, 0xd4, 0xb9, 0x6f, 0xa7, 0xdf, 0xc7, 0x56, 0xb9, 0xd7, 0xfe, 0xd4, 0x3b, 0xfa, 0xbd,
	0x0d, 0xbd, 0xfa, 0xc8, 0x51, 0xb1, 0x5d, 0xa8, 0x7a, 0x02, 0x75, 0x4d, 0xd3, 0xeb, 0x4d, 0xd0,
	0xa5, 0x2d, 0xb7, 0xf5, 0xd4, 0xab, 0x69, 0xaf, 0xd3, 0x3b, 0xf0, 0x96, 0xdd, 0xb4, 0x39, 0x51,
	0xf3, 0x9c, 0x48, 0x35, 0xa7, 0x6b, 0x77, 0xe1, 0x79, 0xf8, 0x86, 0x7d, 0xf5, 0x85, 0x3a, 0x25,
	0x52, 0x3d, 0x58, 0x93, 0x1c, 0x1d, 0x40, 0xc8, 0xe4, 0x3c, 0x65, 0x92, 0xc4, 0x39, 0x4d, 0x4d,
	0x17, 0x7a, 0x18, 0x98, 0x5e, 0x2f, 0x63, 0x19, 0xfe, 0x04, 0x6f, 0xfe, 0x2f, 0x64, 0xb3, 0x19,
	0x7d, 0xdb, 0x8c, 0xf3, 0x66, 0x33, 0xc2, 0xc9, 0xbd, 0xeb, 0x5f, 0x5d, 0x8d, 0x46, 0x1e, 0x9f,
	0x3d, 0x7d, 0xbe, 0xdf, 0xfa, 0xf3, 0xf9, 0xbe, 0xf7, 0xcb, 0xdf, 0xfb, 0x2d, 0x78, 0x3f, 0xe1,
	0xc5, 0x0b, 0x70, 0x8f, 0xdf, 0x98, 0xd6, 0xe0, 0x73, 0xfd, 0xb3, 0x94, 0xdf, 0xf6, 0xea, 0x1f,
	0x7d, 0xdc, 0x35, 0xbf, 0xcf, 0x0f, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x79, 0xe4, 0x00, 0xe6,
	0x19, 0x08, 0x00, 0x00,
}
