// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: util/util.proto

package util // import "github.com/bsm/reason/util"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Vector is an auto-expanding a vector data type.
type Vector struct {
	Data                 []float64 `protobuf:"fixed64,1,rep,packed,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
}

func (m *Vector) Reset()         { *m = Vector{} }
func (m *Vector) String() string { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()    {}
func (*Vector) Descriptor() ([]byte, []int) {
	return fileDescriptor_util_d8ce896256833805, []int{0}
}
func (m *Vector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector.Unmarshal(m, b)
}
func (m *Vector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector.Marshal(b, m, deterministic)
}
func (dst *Vector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector.Merge(dst, src)
}
func (m *Vector) XXX_Size() int {
	return xxx_messageInfo_Vector.Size(m)
}
func (m *Vector) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector.DiscardUnknown(m)
}

var xxx_messageInfo_Vector proto.InternalMessageInfo

// Matrix is an auto-expanding matrix data type.
type Matrix struct {
	Stride               uint32    `protobuf:"varint,1,opt,name=stride,proto3" json:"stride,omitempty"`
	Data                 []float64 `protobuf:"fixed64,2,rep,packed,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
}

func (m *Matrix) Reset()         { *m = Matrix{} }
func (m *Matrix) String() string { return proto.CompactTextString(m) }
func (*Matrix) ProtoMessage()    {}
func (*Matrix) Descriptor() ([]byte, []int) {
	return fileDescriptor_util_d8ce896256833805, []int{1}
}
func (m *Matrix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Matrix.Unmarshal(m, b)
}
func (m *Matrix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Matrix.Marshal(b, m, deterministic)
}
func (dst *Matrix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Matrix.Merge(dst, src)
}
func (m *Matrix) XXX_Size() int {
	return xxx_messageInfo_Matrix.Size(m)
}
func (m *Matrix) XXX_DiscardUnknown() {
	xxx_messageInfo_Matrix.DiscardUnknown(m)
}

var xxx_messageInfo_Matrix proto.InternalMessageInfo

// NumStream allows to extract statistical information from
// a stream of numbers in a single-pass.
type NumStream struct {
	Weight               float64  `protobuf:"fixed64,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Sum                  float64  `protobuf:"fixed64,2,opt,name=sum,proto3" json:"sum,omitempty"`
	SumSquares           float64  `protobuf:"fixed64,3,opt,name=sum_squares,json=sumSquares,proto3" json:"sum_squares,omitempty"`
	Min                  float64  `protobuf:"fixed64,4,opt,name=min,proto3" json:"min,omitempty"`
	Max                  float64  `protobuf:"fixed64,5,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
}

func (m *NumStream) Reset()         { *m = NumStream{} }
func (m *NumStream) String() string { return proto.CompactTextString(m) }
func (*NumStream) ProtoMessage()    {}
func (*NumStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_util_d8ce896256833805, []int{2}
}
func (m *NumStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumStream.Unmarshal(m, b)
}
func (m *NumStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumStream.Marshal(b, m, deterministic)
}
func (dst *NumStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumStream.Merge(dst, src)
}
func (m *NumStream) XXX_Size() int {
	return xxx_messageInfo_NumStream.Size(m)
}
func (m *NumStream) XXX_DiscardUnknown() {
	xxx_messageInfo_NumStream.DiscardUnknown(m)
}

var xxx_messageInfo_NumStream proto.InternalMessageInfo

// NumStreams is an auto-expanding NumStream distribution.
type NumStreams struct {
	Data                 []NumStream `protobuf:"bytes,1,rep,name=data" json:"data"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
}

func (m *NumStreams) Reset()         { *m = NumStreams{} }
func (m *NumStreams) String() string { return proto.CompactTextString(m) }
func (*NumStreams) ProtoMessage()    {}
func (*NumStreams) Descriptor() ([]byte, []int) {
	return fileDescriptor_util_d8ce896256833805, []int{3}
}
func (m *NumStreams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumStreams.Unmarshal(m, b)
}
func (m *NumStreams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumStreams.Marshal(b, m, deterministic)
}
func (dst *NumStreams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumStreams.Merge(dst, src)
}
func (m *NumStreams) XXX_Size() int {
	return xxx_messageInfo_NumStreams.Size(m)
}
func (m *NumStreams) XXX_DiscardUnknown() {
	xxx_messageInfo_NumStreams.DiscardUnknown(m)
}

var xxx_messageInfo_NumStreams proto.InternalMessageInfo

// NumStreamBuckets maintain NumStream information
// in fixed-size buckets.
type NumStreamBuckets struct {
	MaxBuckets           uint32                    `protobuf:"varint,1,opt,name=max_buckets,json=maxBuckets,proto3" json:"max_buckets,omitempty"`
	Buckets              []NumStreamBuckets_Bucket `protobuf:"bytes,2,rep,name=buckets" json:"buckets"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
}

func (m *NumStreamBuckets) Reset()         { *m = NumStreamBuckets{} }
func (m *NumStreamBuckets) String() string { return proto.CompactTextString(m) }
func (*NumStreamBuckets) ProtoMessage()    {}
func (*NumStreamBuckets) Descriptor() ([]byte, []int) {
	return fileDescriptor_util_d8ce896256833805, []int{4}
}
func (m *NumStreamBuckets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumStreamBuckets.Unmarshal(m, b)
}
func (m *NumStreamBuckets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumStreamBuckets.Marshal(b, m, deterministic)
}
func (dst *NumStreamBuckets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumStreamBuckets.Merge(dst, src)
}
func (m *NumStreamBuckets) XXX_Size() int {
	return xxx_messageInfo_NumStreamBuckets.Size(m)
}
func (m *NumStreamBuckets) XXX_DiscardUnknown() {
	xxx_messageInfo_NumStreamBuckets.DiscardUnknown(m)
}

var xxx_messageInfo_NumStreamBuckets proto.InternalMessageInfo

type NumStreamBuckets_Bucket struct {
	Threshold            float64 `protobuf:"fixed64,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	NumStream            `protobuf:"bytes,2,opt,name=stream,embedded=stream" json:"stream"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
}

func (m *NumStreamBuckets_Bucket) Reset()         { *m = NumStreamBuckets_Bucket{} }
func (m *NumStreamBuckets_Bucket) String() string { return proto.CompactTextString(m) }
func (*NumStreamBuckets_Bucket) ProtoMessage()    {}
func (*NumStreamBuckets_Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_util_d8ce896256833805, []int{4, 0}
}
func (m *NumStreamBuckets_Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumStreamBuckets_Bucket.Unmarshal(m, b)
}
func (m *NumStreamBuckets_Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumStreamBuckets_Bucket.Marshal(b, m, deterministic)
}
func (dst *NumStreamBuckets_Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumStreamBuckets_Bucket.Merge(dst, src)
}
func (m *NumStreamBuckets_Bucket) XXX_Size() int {
	return xxx_messageInfo_NumStreamBuckets_Bucket.Size(m)
}
func (m *NumStreamBuckets_Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_NumStreamBuckets_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_NumStreamBuckets_Bucket proto.InternalMessageInfo

// Histogram is a probabilistic, fixed-size data structure, able to
// accommodate massive data streams while predicting distributions
// and quantiles much more accurately than a sample-based approach.
type Histogram struct {
	Weight               float64         `protobuf:"fixed64,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Cap                  uint32          `protobuf:"varint,2,opt,name=cap,proto3" json:"cap,omitempty"`
	Min                  float64         `protobuf:"fixed64,3,opt,name=min,proto3" json:"min,omitempty"`
	Max                  float64         `protobuf:"fixed64,4,opt,name=max,proto3" json:"max,omitempty"`
	Bins                 []Histogram_Bin `protobuf:"bytes,5,rep,name=bins" json:"bins"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
}

func (m *Histogram) Reset()         { *m = Histogram{} }
func (m *Histogram) String() string { return proto.CompactTextString(m) }
func (*Histogram) ProtoMessage()    {}
func (*Histogram) Descriptor() ([]byte, []int) {
	return fileDescriptor_util_d8ce896256833805, []int{5}
}
func (m *Histogram) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Histogram.Unmarshal(m, b)
}
func (m *Histogram) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Histogram.Marshal(b, m, deterministic)
}
func (dst *Histogram) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Histogram.Merge(dst, src)
}
func (m *Histogram) XXX_Size() int {
	return xxx_messageInfo_Histogram.Size(m)
}
func (m *Histogram) XXX_DiscardUnknown() {
	xxx_messageInfo_Histogram.DiscardUnknown(m)
}

var xxx_messageInfo_Histogram proto.InternalMessageInfo

type Histogram_Bin struct {
	Value                float64  `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Weight               float64  `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
}

func (m *Histogram_Bin) Reset()         { *m = Histogram_Bin{} }
func (m *Histogram_Bin) String() string { return proto.CompactTextString(m) }
func (*Histogram_Bin) ProtoMessage()    {}
func (*Histogram_Bin) Descriptor() ([]byte, []int) {
	return fileDescriptor_util_d8ce896256833805, []int{5, 0}
}
func (m *Histogram_Bin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Histogram_Bin.Unmarshal(m, b)
}
func (m *Histogram_Bin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Histogram_Bin.Marshal(b, m, deterministic)
}
func (dst *Histogram_Bin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Histogram_Bin.Merge(dst, src)
}
func (m *Histogram_Bin) XXX_Size() int {
	return xxx_messageInfo_Histogram_Bin.Size(m)
}
func (m *Histogram_Bin) XXX_DiscardUnknown() {
	xxx_messageInfo_Histogram_Bin.DiscardUnknown(m)
}

var xxx_messageInfo_Histogram_Bin proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Vector)(nil), "blacksquaremedia.reason.util.Vector")
	proto.RegisterType((*Matrix)(nil), "blacksquaremedia.reason.util.Matrix")
	proto.RegisterType((*NumStream)(nil), "blacksquaremedia.reason.util.NumStream")
	proto.RegisterType((*NumStreams)(nil), "blacksquaremedia.reason.util.NumStreams")
	proto.RegisterType((*NumStreamBuckets)(nil), "blacksquaremedia.reason.util.NumStreamBuckets")
	proto.RegisterType((*NumStreamBuckets_Bucket)(nil), "blacksquaremedia.reason.util.NumStreamBuckets.Bucket")
	proto.RegisterType((*Histogram)(nil), "blacksquaremedia.reason.util.Histogram")
	proto.RegisterType((*Histogram_Bin)(nil), "blacksquaremedia.reason.util.Histogram.Bin")
}

func init() { proto.RegisterFile("util/util.proto", fileDescriptor_util_d8ce896256833805) }

var fileDescriptor_util_d8ce896256833805 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4f, 0x6b, 0xdc, 0x3e,
	0x10, 0x5d, 0xd9, 0x5e, 0xff, 0x7e, 0x3b, 0x21, 0x74, 0x11, 0x25, 0x98, 0x6d, 0xd8, 0x5d, 0xf6,
	0xd2, 0x40, 0xa9, 0x17, 0x1a, 0x0a, 0xbd, 0xd6, 0x50, 0x68, 0x0f, 0xfd, 0x83, 0xc3, 0xf6, 0xd0,
	0x4b, 0x90, 0xbd, 0xaa, 0x57, 0xc4, 0xb2, 0x12, 0x4b, 0x6a, 0x4d, 0x3f, 0x45, 0x3f, 0x56, 0x8e,
	0xb9, 0x14, 0x7a, 0x0a, 0x84, 0x7c, 0x8e, 0x42, 0x91, 0x64, 0x3b, 0x4b, 0x4b, 0x97, 0xf6, 0x62,
	0xeb, 0xcd, 0xe8, 0x69, 0xde, 0xcc, 0x63, 0xe0, 0x9e, 0x56, 0xac, 0x5c, 0x9a, 0x4f, 0x7c, 0x5e,
	0x0b, 0x25, 0xf0, 0x61, 0x56, 0x92, 0xfc, 0x4c, 0x5e, 0x68, 0x52, 0x53, 0x4e, 0xd7, 0x8c, 0xc4,
	0x35, 0x25, 0x52, 0x54, 0xb1, 0xb9, 0x33, 0x79, 0x5c, 0x30, 0xb5, 0xd1, 0x59, 0x9c, 0x0b, 0xbe,
	0x2c, 0x44, 0x21, 0x96, 0x96, 0x94, 0xe9, 0x8f, 0x16, 0x59, 0x60, 0x4f, 0xee, 0xb1, 0xc5, 0x1c,
	0xc2, 0xf7, 0x34, 0x57, 0xa2, 0xc6, 0x07, 0x10, 0xac, 0x89, 0x22, 0x11, 0x9a, 0xfb, 0x47, 0x28,
	0xf1, 0xc6, 0x28, 0xb5, 0x78, 0xf1, 0x0c, 0xc2, 0xd7, 0x44, 0xd5, 0xac, 0xc1, 0x07, 0x10, 0x4a,
	0x55, 0xb3, 0x35, 0x8d, 0xd0, 0x1c, 0x1d, 0xed, 0xa7, 0x2d, 0xea, 0x99, 0xde, 0x2f, 0xcc, 0x2f,
	0x30, 0x7a, 0xa3, 0xf9, 0x89, 0xaa, 0x29, 0xe1, 0x86, 0xfc, 0x99, 0xb2, 0x62, 0xa3, 0x2c, 0x19,
	0xa5, 0x2d, 0xc2, 0x63, 0xf0, 0xa5, 0xe6, 0x91, 0x67, 0x83, 0xe6, 0x88, 0x67, 0xb0, 0x27, 0x35,
	0x3f, 0x75, 0x0d, 0xca, 0xc8, 0xb7, 0x19, 0x90, 0x9a, 0x9f, 0xb8, 0x88, 0xa1, 0x70, 0x56, 0x45,
	0x81, 0xa3, 0x70, 0x56, 0xd9, 0x08, 0x69, 0xa2, 0x61, 0x1b, 0x21, 0xcd, 0xe2, 0x2d, 0x40, 0x5f,
	0x5b, 0xe2, 0xe7, 0x5b, 0xbd, 0xed, 0x3d, 0x79, 0x18, 0xef, 0x9a, 0x60, 0xdc, 0xf3, 0x92, 0xe0,
	0xf2, 0x7a, 0x36, 0x68, 0x9b, 0xf9, 0x81, 0x60, 0x7c, 0x97, 0xd1, 0xf9, 0x19, 0x55, 0xd2, 0x48,
	0xe5, 0xa4, 0x39, 0xcd, 0x1c, 0x6c, 0xc7, 0x02, 0x9c, 0x34, 0xdd, 0x85, 0x15, 0xfc, 0xd7, 0x25,
	0x3d, 0x5b, 0xfb, 0xe9, 0xdf, 0xd6, 0x76, 0xac, 0xd8, 0xfd, 0x5b, 0x25, 0xdd, 0x5b, 0x93, 0x0b,
	0x08, 0x5d, 0x02, 0x1f, 0xc2, 0x48, 0x6d, 0x6a, 0x2a, 0x37, 0xa2, 0x5c, 0xb7, 0x93, 0xbd, 0x0b,
	0xe0, 0x57, 0xd6, 0x31, 0x4a, 0xdc, 0x7c, 0xff, 0xa1, 0xf3, 0xff, 0x4d, 0xbd, 0xab, 0xeb, 0x19,
	0x4a, 0xdb, 0x07, 0x16, 0xdf, 0x10, 0x8c, 0x5e, 0x32, 0xa9, 0x44, 0x51, 0xef, 0x76, 0x33, 0x27,
	0xe7, 0xb6, 0xda, 0x7e, 0x6a, 0x8e, 0x9d, 0x59, 0xfe, 0x6f, 0x66, 0x05, 0xbd, 0x59, 0xf8, 0x05,
	0x04, 0x19, 0xab, 0x64, 0x34, 0xb4, 0x23, 0x7a, 0xb4, 0x5b, 0x64, 0x2f, 0x22, 0x4e, 0x58, 0xd5,
	0x59, 0x64, 0xe8, 0x93, 0x63, 0xf0, 0x13, 0x56, 0xe1, 0xfb, 0x30, 0xfc, 0x44, 0x4a, 0x4d, 0x5b,
	0x69, 0x0e, 0x6c, 0x29, 0xf6, 0xb6, 0x15, 0x27, 0xab, 0xcb, 0x9b, 0xe9, 0xe0, 0xfb, 0xcd, 0x14,
	0x7d, 0xbd, 0x9d, 0x0e, 0xae, 0x6e, 0xa7, 0x03, 0x78, 0x90, 0x0b, 0xfe, 0x27, 0x09, 0x09, 0xac,
	0x14, 0x2b, 0xdf, 0x99, 0xd5, 0x91, 0x1f, 0x26, 0x5b, 0xab, 0x96, 0x49, 0xbe, 0x74, 0x57, 0xec,
	0xaa, 0x66, 0xa1, 0x5d, 0xaf, 0xe3, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x1e, 0xbc, 0xcd,
	0xbe, 0x03, 0x00, 0x00,
}
