// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: util/util.proto

package util // import "github.com/bsm/reason/util"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Vector is an auto-expanding a vector data type.
type Vector struct {
	Data                 []float64 `protobuf:"fixed64,1,rep,packed,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
}

func (m *Vector) Reset()         { *m = Vector{} }
func (m *Vector) String() string { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()    {}
func (*Vector) Descriptor() ([]byte, []int) {
	return fileDescriptor_util_1f14ee5c804a9981, []int{0}
}
func (m *Vector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector.Unmarshal(m, b)
}
func (m *Vector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector.Marshal(b, m, deterministic)
}
func (dst *Vector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector.Merge(dst, src)
}
func (m *Vector) XXX_Size() int {
	return xxx_messageInfo_Vector.Size(m)
}
func (m *Vector) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector.DiscardUnknown(m)
}

var xxx_messageInfo_Vector proto.InternalMessageInfo

// Matrix is an auto-expanding matrix data type.
type Matrix struct {
	Stride               uint32    `protobuf:"varint,1,opt,name=stride,proto3" json:"stride,omitempty"`
	Data                 []float64 `protobuf:"fixed64,2,rep,packed,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
}

func (m *Matrix) Reset()         { *m = Matrix{} }
func (m *Matrix) String() string { return proto.CompactTextString(m) }
func (*Matrix) ProtoMessage()    {}
func (*Matrix) Descriptor() ([]byte, []int) {
	return fileDescriptor_util_1f14ee5c804a9981, []int{1}
}
func (m *Matrix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Matrix.Unmarshal(m, b)
}
func (m *Matrix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Matrix.Marshal(b, m, deterministic)
}
func (dst *Matrix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Matrix.Merge(dst, src)
}
func (m *Matrix) XXX_Size() int {
	return xxx_messageInfo_Matrix.Size(m)
}
func (m *Matrix) XXX_DiscardUnknown() {
	xxx_messageInfo_Matrix.DiscardUnknown(m)
}

var xxx_messageInfo_Matrix proto.InternalMessageInfo

// NumStream allows to extract statistical information from
// a stream of numbers in a single-pass.
type NumStream struct {
	Weight               float64  `protobuf:"fixed64,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Sum                  float64  `protobuf:"fixed64,2,opt,name=sum,proto3" json:"sum,omitempty"`
	SumSquares           float64  `protobuf:"fixed64,3,opt,name=sum_squares,json=sumSquares,proto3" json:"sum_squares,omitempty"`
	Min                  float64  `protobuf:"fixed64,4,opt,name=min,proto3" json:"min,omitempty"`
	Max                  float64  `protobuf:"fixed64,5,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
}

func (m *NumStream) Reset()         { *m = NumStream{} }
func (m *NumStream) String() string { return proto.CompactTextString(m) }
func (*NumStream) ProtoMessage()    {}
func (*NumStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_util_1f14ee5c804a9981, []int{2}
}
func (m *NumStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumStream.Unmarshal(m, b)
}
func (m *NumStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumStream.Marshal(b, m, deterministic)
}
func (dst *NumStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumStream.Merge(dst, src)
}
func (m *NumStream) XXX_Size() int {
	return xxx_messageInfo_NumStream.Size(m)
}
func (m *NumStream) XXX_DiscardUnknown() {
	xxx_messageInfo_NumStream.DiscardUnknown(m)
}

var xxx_messageInfo_NumStream proto.InternalMessageInfo

// NumStreams is an auto-expanding NumStream distribution.
type NumStreams struct {
	Data                 []NumStream `protobuf:"bytes,1,rep,name=data" json:"data"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
}

func (m *NumStreams) Reset()         { *m = NumStreams{} }
func (m *NumStreams) String() string { return proto.CompactTextString(m) }
func (*NumStreams) ProtoMessage()    {}
func (*NumStreams) Descriptor() ([]byte, []int) {
	return fileDescriptor_util_1f14ee5c804a9981, []int{3}
}
func (m *NumStreams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumStreams.Unmarshal(m, b)
}
func (m *NumStreams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumStreams.Marshal(b, m, deterministic)
}
func (dst *NumStreams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumStreams.Merge(dst, src)
}
func (m *NumStreams) XXX_Size() int {
	return xxx_messageInfo_NumStreams.Size(m)
}
func (m *NumStreams) XXX_DiscardUnknown() {
	xxx_messageInfo_NumStreams.DiscardUnknown(m)
}

var xxx_messageInfo_NumStreams proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Vector)(nil), "blacksquaremedia.reason.util.Vector")
	proto.RegisterType((*Matrix)(nil), "blacksquaremedia.reason.util.Matrix")
	proto.RegisterType((*NumStream)(nil), "blacksquaremedia.reason.util.NumStream")
	proto.RegisterType((*NumStreams)(nil), "blacksquaremedia.reason.util.NumStreams")
}

func init() { proto.RegisterFile("util/util.proto", fileDescriptor_util_1f14ee5c804a9981) }

var fileDescriptor_util_1f14ee5c804a9981 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4d, 0x4b, 0x3b, 0x31,
	0x10, 0xc6, 0x37, 0x6d, 0xff, 0x0b, 0xff, 0x29, 0x62, 0xd9, 0x43, 0x09, 0x55, 0xb6, 0xa5, 0x17,
	0x7b, 0x31, 0x0b, 0x7a, 0xf1, 0xea, 0xde, 0x7d, 0xa1, 0xa5, 0x1e, 0xbc, 0x48, 0x76, 0x1b, 0xb7,
	0xc1, 0xa6, 0xd1, 0xbc, 0x60, 0xf1, 0x53, 0xf8, 0xb1, 0x7a, 0xf4, 0xe8, 0x49, 0x28, 0xfd, 0x22,
	0x92, 0xa4, 0x2c, 0x45, 0xd0, 0xcb, 0x32, 0xcf, 0xb3, 0xf3, 0x9b, 0x30, 0xf3, 0xc0, 0xa1, 0x35,
	0x7c, 0x91, 0xb9, 0x0f, 0x79, 0x56, 0xd2, 0xc8, 0xe4, 0xb8, 0x58, 0xd0, 0xf2, 0x49, 0xbf, 0x58,
	0xaa, 0x98, 0x60, 0x33, 0x4e, 0x89, 0x62, 0x54, 0xcb, 0x25, 0x71, 0x3d, 0xbd, 0xd3, 0x8a, 0x9b,
	0xb9, 0x2d, 0x48, 0x29, 0x45, 0x56, 0xc9, 0x4a, 0x66, 0x1e, 0x2a, 0xec, 0xa3, 0x57, 0x5e, 0xf8,
	0x2a, 0x0c, 0x1b, 0x0e, 0x20, 0xbe, 0x63, 0xa5, 0x91, 0x2a, 0xe9, 0x42, 0x6b, 0x46, 0x0d, 0xc5,
	0x68, 0xd0, 0x1c, 0xa1, 0xbc, 0xd1, 0x41, 0x63, 0xaf, 0x87, 0x17, 0x10, 0x5f, 0x51, 0xa3, 0xf8,
	0x2a, 0xe9, 0x42, 0xac, 0x8d, 0xe2, 0x33, 0x86, 0xd1, 0x00, 0x8d, 0x0e, 0xc6, 0x3b, 0x55, 0x93,
	0x8d, 0x1f, 0xe4, 0x1b, 0xfc, 0xbf, 0xb6, 0x62, 0x62, 0x14, 0xa3, 0xc2, 0xc1, 0xaf, 0x8c, 0x57,
	0x73, 0xe3, 0x61, 0x34, 0xde, 0xa9, 0xa4, 0x03, 0x4d, 0x6d, 0x05, 0x6e, 0x78, 0xd3, 0x95, 0x49,
	0x1f, 0xda, 0xda, 0x8a, 0x87, 0xb0, 0xa0, 0xc6, 0x4d, 0xff, 0x07, 0xb4, 0x15, 0x93, 0xe0, 0x38,
	0x44, 0xf0, 0x25, 0x6e, 0x05, 0x44, 0xf0, 0xa5, 0x77, 0xe8, 0x0a, 0xff, 0xdb, 0x39, 0x74, 0x35,
	0xbc, 0x01, 0xa8, 0xdf, 0xd6, 0xc9, 0xe5, 0xde, 0x6e, 0xed, 0xb3, 0x13, 0xf2, 0xd7, 0x05, 0x49,
	0xcd, 0xe5, 0xad, 0xf5, 0x57, 0x3f, 0x0a, 0xcb, 0xe4, 0xd3, 0xf5, 0x26, 0x8d, 0x3e, 0x37, 0x29,
	0x7a, 0xdf, 0xa6, 0xd1, 0xc7, 0x36, 0x8d, 0xe0, 0xa8, 0x94, 0xe2, 0xb7, 0x49, 0x39, 0x4c, 0x0d,
	0x5f, 0xdc, 0xba, 0x13, 0xeb, 0xfb, 0xde, 0x5e, 0x24, 0x85, 0x16, 0x59, 0x68, 0xf1, 0x91, 0x16,
	0xb1, 0x8f, 0xe1, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xb8, 0x21, 0xbf, 0xe6, 0x01, 0x00,
	0x00,
}
