// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: classifier/hoeffding/internal/internal.proto

package internal // import "github.com/bsm/reason/classifier/hoeffding/internal"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/bsm/reason/core"
import util "github.com/bsm/reason/util"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Tree wraps the tree data.
type Tree struct {
	// The underlying model.
	Model *core.Model `protobuf:"bytes,1,opt,name=model" json:"model,omitempty"`
	// The target feature.
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// The root nodeRef.
	Root int64 `protobuf:"varint,3,opt,name=root,proto3" json:"root,omitempty"`
	// The node registry.
	Nodes                []*Node  `protobuf:"bytes,4,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
}

func (m *Tree) Reset()         { *m = Tree{} }
func (m *Tree) String() string { return proto.CompactTextString(m) }
func (*Tree) ProtoMessage()    {}
func (*Tree) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_f1078f466b7f1db7, []int{0}
}
func (m *Tree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tree.Unmarshal(m, b)
}
func (m *Tree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tree.Marshal(b, m, deterministic)
}
func (dst *Tree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tree.Merge(dst, src)
}
func (m *Tree) XXX_Size() int {
	return xxx_messageInfo_Tree.Size(m)
}
func (m *Tree) XXX_DiscardUnknown() {
	xxx_messageInfo_Tree.DiscardUnknown(m)
}

var xxx_messageInfo_Tree proto.InternalMessageInfo

// FeatureStats instances maintain stats based on
// observation of a particular feature.
type FeatureStats struct {
	// Types that are valid to be assigned to Kind:
	//	*FeatureStats_ClsNum
	//	*FeatureStats_ClsCat
	//	*FeatureStats_RegNum
	//	*FeatureStats_RegCat
	Kind                 isFeatureStats_Kind `protobuf_oneof:"kind"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
}

func (m *FeatureStats) Reset()         { *m = FeatureStats{} }
func (m *FeatureStats) String() string { return proto.CompactTextString(m) }
func (*FeatureStats) ProtoMessage()    {}
func (*FeatureStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_f1078f466b7f1db7, []int{1}
}
func (m *FeatureStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureStats.Unmarshal(m, b)
}
func (m *FeatureStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureStats.Marshal(b, m, deterministic)
}
func (dst *FeatureStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureStats.Merge(dst, src)
}
func (m *FeatureStats) XXX_Size() int {
	return xxx_messageInfo_FeatureStats.Size(m)
}
func (m *FeatureStats) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureStats.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureStats proto.InternalMessageInfo

type isFeatureStats_Kind interface {
	isFeatureStats_Kind()
}

type FeatureStats_ClsNum struct {
	ClsNum *FeatureStats_ClassificationNumerical `protobuf:"bytes,1,opt,name=cls_num,json=clsNum,oneof"`
}
type FeatureStats_ClsCat struct {
	ClsCat *FeatureStats_ClassificationCategorical `protobuf:"bytes,2,opt,name=cls_cat,json=clsCat,oneof"`
}
type FeatureStats_RegNum struct {
	RegNum *FeatureStats_RegressionNumerical `protobuf:"bytes,3,opt,name=reg_num,json=regNum,oneof"`
}
type FeatureStats_RegCat struct {
	RegCat *FeatureStats_RegressionCategorical `protobuf:"bytes,4,opt,name=reg_cat,json=regCat,oneof"`
}

func (*FeatureStats_ClsNum) isFeatureStats_Kind() {}
func (*FeatureStats_ClsCat) isFeatureStats_Kind() {}
func (*FeatureStats_RegNum) isFeatureStats_Kind() {}
func (*FeatureStats_RegCat) isFeatureStats_Kind() {}

func (m *FeatureStats) GetKind() isFeatureStats_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *FeatureStats) GetClsNum() *FeatureStats_ClassificationNumerical {
	if x, ok := m.GetKind().(*FeatureStats_ClsNum); ok {
		return x.ClsNum
	}
	return nil
}

func (m *FeatureStats) GetClsCat() *FeatureStats_ClassificationCategorical {
	if x, ok := m.GetKind().(*FeatureStats_ClsCat); ok {
		return x.ClsCat
	}
	return nil
}

func (m *FeatureStats) GetRegNum() *FeatureStats_RegressionNumerical {
	if x, ok := m.GetKind().(*FeatureStats_RegNum); ok {
		return x.RegNum
	}
	return nil
}

func (m *FeatureStats) GetRegCat() *FeatureStats_RegressionCategorical {
	if x, ok := m.GetKind().(*FeatureStats_RegCat); ok {
		return x.RegCat
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FeatureStats) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FeatureStats_OneofMarshaler, _FeatureStats_OneofUnmarshaler, _FeatureStats_OneofSizer, []interface{}{
		(*FeatureStats_ClsNum)(nil),
		(*FeatureStats_ClsCat)(nil),
		(*FeatureStats_RegNum)(nil),
		(*FeatureStats_RegCat)(nil),
	}
}

func _FeatureStats_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FeatureStats)
	// kind
	switch x := m.Kind.(type) {
	case *FeatureStats_ClsNum:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClsNum); err != nil {
			return err
		}
	case *FeatureStats_ClsCat:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClsCat); err != nil {
			return err
		}
	case *FeatureStats_RegNum:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RegNum); err != nil {
			return err
		}
	case *FeatureStats_RegCat:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RegCat); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("FeatureStats.Kind has unexpected type %T", x)
	}
	return nil
}

func _FeatureStats_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FeatureStats)
	switch tag {
	case 1: // kind.cls_num
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FeatureStats_ClassificationNumerical)
		err := b.DecodeMessage(msg)
		m.Kind = &FeatureStats_ClsNum{msg}
		return true, err
	case 2: // kind.cls_cat
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FeatureStats_ClassificationCategorical)
		err := b.DecodeMessage(msg)
		m.Kind = &FeatureStats_ClsCat{msg}
		return true, err
	case 3: // kind.reg_num
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FeatureStats_RegressionNumerical)
		err := b.DecodeMessage(msg)
		m.Kind = &FeatureStats_RegNum{msg}
		return true, err
	case 4: // kind.reg_cat
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FeatureStats_RegressionCategorical)
		err := b.DecodeMessage(msg)
		m.Kind = &FeatureStats_RegCat{msg}
		return true, err
	default:
		return false, nil
	}
}

func _FeatureStats_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FeatureStats)
	// kind
	switch x := m.Kind.(type) {
	case *FeatureStats_ClsNum:
		s := proto.Size(x.ClsNum)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *FeatureStats_ClsCat:
		s := proto.Size(x.ClsCat)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *FeatureStats_RegNum:
		s := proto.Size(x.RegNum)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *FeatureStats_RegCat:
		s := proto.Size(x.RegCat)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type FeatureStats_ClassificationNumerical struct {
	Min                  util.Vector `protobuf:"bytes,1,opt,name=min" json:"min"`
	Max                  util.Vector `protobuf:"bytes,2,opt,name=max" json:"max"`
	Stats                util.Matrix `protobuf:"bytes,3,opt,name=stats" json:"stats"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
}

func (m *FeatureStats_ClassificationNumerical) Reset()         { *m = FeatureStats_ClassificationNumerical{} }
func (m *FeatureStats_ClassificationNumerical) String() string { return proto.CompactTextString(m) }
func (*FeatureStats_ClassificationNumerical) ProtoMessage()    {}
func (*FeatureStats_ClassificationNumerical) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_f1078f466b7f1db7, []int{1, 0}
}
func (m *FeatureStats_ClassificationNumerical) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureStats_ClassificationNumerical.Unmarshal(m, b)
}
func (m *FeatureStats_ClassificationNumerical) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureStats_ClassificationNumerical.Marshal(b, m, deterministic)
}
func (dst *FeatureStats_ClassificationNumerical) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureStats_ClassificationNumerical.Merge(dst, src)
}
func (m *FeatureStats_ClassificationNumerical) XXX_Size() int {
	return xxx_messageInfo_FeatureStats_ClassificationNumerical.Size(m)
}
func (m *FeatureStats_ClassificationNumerical) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureStats_ClassificationNumerical.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureStats_ClassificationNumerical proto.InternalMessageInfo

type FeatureStats_ClassificationCategorical struct {
	util.Matrix          `protobuf:"bytes,1,opt,name=stats,embedded=stats" json:"stats"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
}

func (m *FeatureStats_ClassificationCategorical) Reset() {
	*m = FeatureStats_ClassificationCategorical{}
}
func (m *FeatureStats_ClassificationCategorical) String() string { return proto.CompactTextString(m) }
func (*FeatureStats_ClassificationCategorical) ProtoMessage()    {}
func (*FeatureStats_ClassificationCategorical) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_f1078f466b7f1db7, []int{1, 1}
}
func (m *FeatureStats_ClassificationCategorical) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureStats_ClassificationCategorical.Unmarshal(m, b)
}
func (m *FeatureStats_ClassificationCategorical) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureStats_ClassificationCategorical.Marshal(b, m, deterministic)
}
func (dst *FeatureStats_ClassificationCategorical) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureStats_ClassificationCategorical.Merge(dst, src)
}
func (m *FeatureStats_ClassificationCategorical) XXX_Size() int {
	return xxx_messageInfo_FeatureStats_ClassificationCategorical.Size(m)
}
func (m *FeatureStats_ClassificationCategorical) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureStats_ClassificationCategorical.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureStats_ClassificationCategorical proto.InternalMessageInfo

type FeatureStats_RegressionNumerical struct {
	Min                  float64                                        `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  float64                                        `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	Observations         []FeatureStats_RegressionNumerical_Observation `protobuf:"bytes,3,rep,name=observations" json:"observations"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
}

func (m *FeatureStats_RegressionNumerical) Reset()         { *m = FeatureStats_RegressionNumerical{} }
func (m *FeatureStats_RegressionNumerical) String() string { return proto.CompactTextString(m) }
func (*FeatureStats_RegressionNumerical) ProtoMessage()    {}
func (*FeatureStats_RegressionNumerical) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_f1078f466b7f1db7, []int{1, 2}
}
func (m *FeatureStats_RegressionNumerical) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureStats_RegressionNumerical.Unmarshal(m, b)
}
func (m *FeatureStats_RegressionNumerical) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureStats_RegressionNumerical.Marshal(b, m, deterministic)
}
func (dst *FeatureStats_RegressionNumerical) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureStats_RegressionNumerical.Merge(dst, src)
}
func (m *FeatureStats_RegressionNumerical) XXX_Size() int {
	return xxx_messageInfo_FeatureStats_RegressionNumerical.Size(m)
}
func (m *FeatureStats_RegressionNumerical) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureStats_RegressionNumerical.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureStats_RegressionNumerical proto.InternalMessageInfo

type FeatureStats_RegressionNumerical_Observation struct {
	FeatureValue         float64  `protobuf:"fixed64,1,opt,name=feature_value,json=featureValue,proto3" json:"feature_value,omitempty"`
	TargetValue          float64  `protobuf:"fixed64,2,opt,name=target_value,json=targetValue,proto3" json:"target_value,omitempty"`
	Weight               float64  `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
}

func (m *FeatureStats_RegressionNumerical_Observation) Reset() {
	*m = FeatureStats_RegressionNumerical_Observation{}
}
func (m *FeatureStats_RegressionNumerical_Observation) String() string {
	return proto.CompactTextString(m)
}
func (*FeatureStats_RegressionNumerical_Observation) ProtoMessage() {}
func (*FeatureStats_RegressionNumerical_Observation) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_f1078f466b7f1db7, []int{1, 2, 0}
}
func (m *FeatureStats_RegressionNumerical_Observation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureStats_RegressionNumerical_Observation.Unmarshal(m, b)
}
func (m *FeatureStats_RegressionNumerical_Observation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureStats_RegressionNumerical_Observation.Marshal(b, m, deterministic)
}
func (dst *FeatureStats_RegressionNumerical_Observation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureStats_RegressionNumerical_Observation.Merge(dst, src)
}
func (m *FeatureStats_RegressionNumerical_Observation) XXX_Size() int {
	return xxx_messageInfo_FeatureStats_RegressionNumerical_Observation.Size(m)
}
func (m *FeatureStats_RegressionNumerical_Observation) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureStats_RegressionNumerical_Observation.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureStats_RegressionNumerical_Observation proto.InternalMessageInfo

type FeatureStats_RegressionCategorical struct {
	util.Matrix          `protobuf:"bytes,1,opt,name=stats,embedded=stats" json:"stats"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
}

func (m *FeatureStats_RegressionCategorical) Reset()         { *m = FeatureStats_RegressionCategorical{} }
func (m *FeatureStats_RegressionCategorical) String() string { return proto.CompactTextString(m) }
func (*FeatureStats_RegressionCategorical) ProtoMessage()    {}
func (*FeatureStats_RegressionCategorical) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_f1078f466b7f1db7, []int{1, 3}
}
func (m *FeatureStats_RegressionCategorical) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureStats_RegressionCategorical.Unmarshal(m, b)
}
func (m *FeatureStats_RegressionCategorical) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureStats_RegressionCategorical.Marshal(b, m, deterministic)
}
func (dst *FeatureStats_RegressionCategorical) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureStats_RegressionCategorical.Merge(dst, src)
}
func (m *FeatureStats_RegressionCategorical) XXX_Size() int {
	return xxx_messageInfo_FeatureStats_RegressionCategorical.Size(m)
}
func (m *FeatureStats_RegressionCategorical) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureStats_RegressionCategorical.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureStats_RegressionCategorical proto.InternalMessageInfo

// Node is a tree node
type Node struct {
	// Observation stats for the node
	Stats *util.Vector `protobuf:"bytes,1,opt,name=stats" json:"stats,omitempty"`
	// Nodes can be leaf or split nodes.
	//
	// Types that are valid to be assigned to Kind:
	//	*Node_Leaf
	//	*Node_Split
	Kind                 isNode_Kind `protobuf_oneof:"kind"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_f1078f466b7f1db7, []int{2}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

type isNode_Kind interface {
	isNode_Kind()
}

type Node_Leaf struct {
	Leaf *LeafNode `protobuf:"bytes,2,opt,name=leaf,oneof"`
}
type Node_Split struct {
	Split *SplitNode `protobuf:"bytes,3,opt,name=split,oneof"`
}

func (*Node_Leaf) isNode_Kind()  {}
func (*Node_Split) isNode_Kind() {}

func (m *Node) GetKind() isNode_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *Node) GetLeaf() *LeafNode {
	if x, ok := m.GetKind().(*Node_Leaf); ok {
		return x.Leaf
	}
	return nil
}

func (m *Node) GetSplit() *SplitNode {
	if x, ok := m.GetKind().(*Node_Split); ok {
		return x.Split
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Node) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Node_OneofMarshaler, _Node_OneofUnmarshaler, _Node_OneofSizer, []interface{}{
		(*Node_Leaf)(nil),
		(*Node_Split)(nil),
	}
}

func _Node_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Node)
	// kind
	switch x := m.Kind.(type) {
	case *Node_Leaf:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Leaf); err != nil {
			return err
		}
	case *Node_Split:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Split); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Node.Kind has unexpected type %T", x)
	}
	return nil
}

func _Node_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Node)
	switch tag {
	case 2: // kind.leaf
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LeafNode)
		err := b.DecodeMessage(msg)
		m.Kind = &Node_Leaf{msg}
		return true, err
	case 3: // kind.split
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SplitNode)
		err := b.DecodeMessage(msg)
		m.Kind = &Node_Split{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Node_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Node)
	// kind
	switch x := m.Kind.(type) {
	case *Node_Leaf:
		s := proto.Size(x.Leaf)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Node_Split:
		s := proto.Size(x.Split)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// SplitNode instances are intermediate nodes within the tree.
type SplitNode struct {
	// The feature name (predictor).
	Feature string `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	// The pivot value for binary splits (numerical predictors).
	Pivot float64 `protobuf:"fixed64,2,opt,name=pivot,proto3" json:"pivot,omitempty"`
	// The child references.
	Children             []int64  `protobuf:"varint,3,rep,packed,name=children" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
}

func (m *SplitNode) Reset()         { *m = SplitNode{} }
func (m *SplitNode) String() string { return proto.CompactTextString(m) }
func (*SplitNode) ProtoMessage()    {}
func (*SplitNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_f1078f466b7f1db7, []int{3}
}
func (m *SplitNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SplitNode.Unmarshal(m, b)
}
func (m *SplitNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SplitNode.Marshal(b, m, deterministic)
}
func (dst *SplitNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SplitNode.Merge(dst, src)
}
func (m *SplitNode) XXX_Size() int {
	return xxx_messageInfo_SplitNode.Size(m)
}
func (m *SplitNode) XXX_DiscardUnknown() {
	xxx_messageInfo_SplitNode.DiscardUnknown(m)
}

var xxx_messageInfo_SplitNode proto.InternalMessageInfo

// LeafNode instances are the leaves within the tree.
type LeafNode struct {
	// Observation stats, but feature.
	FeatureStats map[string]*FeatureStats `protobuf:"bytes,1,rep,name=feature_stats,json=featureStats" json:"feature_stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	// Weight at the time of the last split evaluation.
	WeightAtLastEval float64 `protobuf:"fixed64,2,opt,name=weight_at_last_eval,json=weightAtLastEval,proto3" json:"weight_at_last_eval,omitempty"`
	// Status indicator.
	IsDisabled           bool     `protobuf:"varint,3,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
}

func (m *LeafNode) Reset()         { *m = LeafNode{} }
func (m *LeafNode) String() string { return proto.CompactTextString(m) }
func (*LeafNode) ProtoMessage()    {}
func (*LeafNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_f1078f466b7f1db7, []int{4}
}
func (m *LeafNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeafNode.Unmarshal(m, b)
}
func (m *LeafNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeafNode.Marshal(b, m, deterministic)
}
func (dst *LeafNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeafNode.Merge(dst, src)
}
func (m *LeafNode) XXX_Size() int {
	return xxx_messageInfo_LeafNode.Size(m)
}
func (m *LeafNode) XXX_DiscardUnknown() {
	xxx_messageInfo_LeafNode.DiscardUnknown(m)
}

var xxx_messageInfo_LeafNode proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Tree)(nil), "blacksquaremedia.reason.classifier.hoeffding.Tree")
	proto.RegisterType((*FeatureStats)(nil), "blacksquaremedia.reason.classifier.hoeffding.FeatureStats")
	proto.RegisterType((*FeatureStats_ClassificationNumerical)(nil), "blacksquaremedia.reason.classifier.hoeffding.FeatureStats.ClassificationNumerical")
	proto.RegisterType((*FeatureStats_ClassificationCategorical)(nil), "blacksquaremedia.reason.classifier.hoeffding.FeatureStats.ClassificationCategorical")
	proto.RegisterType((*FeatureStats_RegressionNumerical)(nil), "blacksquaremedia.reason.classifier.hoeffding.FeatureStats.RegressionNumerical")
	proto.RegisterType((*FeatureStats_RegressionNumerical_Observation)(nil), "blacksquaremedia.reason.classifier.hoeffding.FeatureStats.RegressionNumerical.Observation")
	proto.RegisterType((*FeatureStats_RegressionCategorical)(nil), "blacksquaremedia.reason.classifier.hoeffding.FeatureStats.RegressionCategorical")
	proto.RegisterType((*Node)(nil), "blacksquaremedia.reason.classifier.hoeffding.Node")
	proto.RegisterType((*SplitNode)(nil), "blacksquaremedia.reason.classifier.hoeffding.SplitNode")
	proto.RegisterType((*LeafNode)(nil), "blacksquaremedia.reason.classifier.hoeffding.LeafNode")
	proto.RegisterMapType((map[string]*FeatureStats)(nil), "blacksquaremedia.reason.classifier.hoeffding.LeafNode.FeatureStatsEntry")
}

func init() {
	proto.RegisterFile("classifier/hoeffding/internal/internal.proto", fileDescriptor_internal_f1078f466b7f1db7)
}

var fileDescriptor_internal_f1078f466b7f1db7 = []byte{
	// 843 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0x5b, 0x45,
	0x14, 0xf6, 0xf8, 0x2f, 0xc9, 0x71, 0x50, 0xc2, 0x14, 0x8a, 0xf1, 0xc2, 0x09, 0x29, 0x42, 0x59,
	0xb4, 0xd7, 0x92, 0x2b, 0xf1, 0x13, 0xb1, 0x00, 0xa7, 0x45, 0x5e, 0xa4, 0x69, 0x74, 0x5b, 0x75,
	0x51, 0x84, 0xac, 0xf1, 0xbd, 0xc7, 0x37, 0xa3, 0xcc, 0xbd, 0x13, 0x66, 0xe6, 0x9a, 0x54, 0x48,
	0xac, 0x78, 0x00, 0x1e, 0x80, 0x77, 0x60, 0xc9, 0x1b, 0xa0, 0x2e, 0xbb, 0x83, 0x55, 0xa5, 0xaa,
	0x2b, 0xde, 0x02, 0xcd, 0x8f, 0xed, 0xb4, 0x34, 0x80, 0x43, 0x36, 0xd6, 0xcc, 0xb9, 0xe7, 0x7c,
	0xdf, 0x7c, 0xe7, 0x7c, 0xf7, 0x7a, 0xe0, 0x66, 0x22, 0x98, 0xd6, 0x7c, 0xc2, 0x51, 0xf5, 0x8e,
	0x25, 0x4e, 0x26, 0x29, 0x2f, 0xb2, 0x1e, 0x2f, 0x0c, 0xaa, 0x82, 0x89, 0xf9, 0x22, 0x3a, 0x55,
	0xd2, 0x48, 0x7a, 0x73, 0x2c, 0x58, 0x72, 0xa2, 0xbf, 0x2d, 0x99, 0xc2, 0x1c, 0x53, 0xce, 0x22,
	0x85, 0x4c, 0xcb, 0x22, 0x5a, 0xa0, 0x44, 0x73, 0x94, 0xce, 0x46, 0x22, 0x15, 0xf6, 0xec, 0x8f,
	0x2f, 0xef, 0x6c, 0x94, 0x86, 0x8b, 0x9e, 0xfd, 0x09, 0x81, 0x5b, 0x19, 0x37, 0xc7, 0xe5, 0x38,
	0x4a, 0x64, 0xde, 0xcb, 0x64, 0x26, 0x7b, 0x2e, 0x3c, 0x2e, 0x27, 0x6e, 0xe7, 0x36, 0x6e, 0xe5,
	0xd3, 0x77, 0x7e, 0x25, 0x50, 0x7f, 0xa8, 0x10, 0xe9, 0x67, 0xd0, 0xc8, 0x65, 0x8a, 0xa2, 0x4d,
	0xb6, 0xc9, 0x6e, 0xab, 0x7f, 0x23, 0xba, 0xf0, 0x5c, 0x96, 0xfc, 0x9e, 0x4d, 0x8d, 0x7d, 0x05,
	0xbd, 0x0e, 0x4d, 0xc3, 0x54, 0x86, 0xa6, 0x5d, 0xdd, 0x26, 0xbb, 0x6b, 0x71, 0xd8, 0x51, 0x0a,
	0x75, 0x25, 0xa5, 0x69, 0xd7, 0xb6, 0xc9, 0x6e, 0x2d, 0x76, 0x6b, 0x3a, 0x84, 0x46, 0x21, 0x53,
	0xd4, 0xed, 0xfa, 0x76, 0x6d, 0xb7, 0xd5, 0xef, 0x47, 0xcb, 0xc8, 0x8f, 0x0e, 0x65, 0x8a, 0xb1,
	0x07, 0xd8, 0xf9, 0x79, 0x0d, 0xd6, 0xbf, 0x42, 0x66, 0x4a, 0x85, 0x0f, 0x0c, 0x33, 0x9a, 0xe6,
	0xb0, 0x92, 0x08, 0x3d, 0x2a, 0xca, 0x3c, 0x68, 0x88, 0x97, 0x03, 0x3f, 0x0f, 0x16, 0xed, 0x87,
	0x8c, 0x84, 0x19, 0x2e, 0x8b, 0xc3, 0x32, 0x47, 0xc5, 0x13, 0x26, 0x86, 0x95, 0xb8, 0x99, 0x08,
	0x7d, 0x58, 0xe6, 0x54, 0x7a, 0xba, 0x84, 0x79, 0xd9, 0xad, 0xfe, 0xc3, 0x2b, 0xa3, 0xdb, 0x67,
	0x06, 0x33, 0x79, 0x9e, 0x70, 0x9f, 0x19, 0xca, 0x61, 0x45, 0x61, 0xe6, 0xf4, 0xd5, 0x1c, 0xe1,
	0xe1, 0xff, 0x20, 0x8c, 0x31, 0x53, 0xa8, 0xf5, 0xeb, 0xda, 0x14, 0x66, 0x56, 0xdb, 0x89, 0xa7,
	0xb2, 0xda, 0xea, 0x8e, 0xea, 0xe8, 0x4a, 0xa8, 0x5e, 0xd3, 0xa5, 0x30, 0xdb, 0x67, 0xa6, 0xf3,
	0x3b, 0x81, 0xf7, 0x2e, 0x68, 0x37, 0xfd, 0x1c, 0x6a, 0x39, 0x2f, 0xc2, 0x3c, 0x3f, 0xbc, 0xf0,
	0x10, 0xce, 0xff, 0x8f, 0x30, 0x31, 0x52, 0x0d, 0xea, 0x4f, 0x9f, 0x6f, 0x55, 0x62, 0x5b, 0xe6,
	0xaa, 0xd9, 0x59, 0x18, 0xcf, 0x72, 0xd5, 0xec, 0x8c, 0x7e, 0x01, 0x0d, 0x6d, 0x05, 0x84, 0x6e,
	0xff, 0x4b, 0xfd, 0x3d, 0x66, 0x14, 0x3f, 0x0b, 0xf5, 0xbe, 0xb0, 0xc3, 0xe0, 0xfd, 0x0b, 0x07,
	0x4b, 0xef, 0xcc, 0xe0, 0xc9, 0x12, 0xf0, 0xab, 0x16, 0xfe, 0xd9, 0xf3, 0x2d, 0x32, 0xa3, 0xf8,
	0xa5, 0x0a, 0xd7, 0xde, 0x30, 0x4b, 0xba, 0xb9, 0x68, 0x1c, 0xf1, 0xcd, 0xd8, 0x5c, 0x34, 0x83,
	0x78, 0x81, 0x3f, 0x12, 0x58, 0x97, 0x63, 0x8d, 0x6a, 0xea, 0x0e, 0x67, 0x85, 0xda, 0x77, 0xf2,
	0xf1, 0xd5, 0xda, 0x2a, 0xba, 0xbf, 0xa0, 0x08, 0xed, 0x79, 0x85, 0xb5, 0x93, 0x43, 0xeb, 0x5c,
	0x0a, 0xbd, 0x01, 0x6f, 0x4d, 0x3c, 0xe4, 0x68, 0xca, 0x44, 0x89, 0x41, 0xc3, 0x7a, 0x08, 0x3e,
	0xb2, 0x31, 0xfa, 0x01, 0xac, 0xfb, 0x8f, 0x4c, 0xc8, 0xf1, 0xaa, 0x5a, 0x3e, 0xe6, 0x53, 0xae,
	0x43, 0xf3, 0x3b, 0xe4, 0xd9, 0xb1, 0xff, 0xfe, 0x90, 0x38, 0xec, 0x3a, 0xdf, 0xc0, 0xbb, 0x6f,
	0x74, 0xe4, 0xd5, 0x0c, 0x64, 0xd0, 0x84, 0xfa, 0x09, 0x2f, 0xd2, 0x9d, 0x3f, 0x09, 0xd4, 0xed,
	0xe7, 0x8a, 0xee, 0x2d, 0x05, 0xeb, 0x6d, 0x18, 0xc0, 0xe8, 0x01, 0xd4, 0x05, 0xb2, 0x49, 0x70,
	0xf0, 0xc7, 0xcb, 0x0d, 0xe6, 0x00, 0xd9, 0xc4, 0x9e, 0x60, 0x58, 0x89, 0x1d, 0x0a, 0xbd, 0x0f,
	0x0d, 0x7d, 0x2a, 0xb8, 0x09, 0x86, 0xfe, 0x64, 0x39, 0xb8, 0x07, 0xb6, 0x34, 0xe0, 0x79, 0x9c,
	0xb9, 0xd6, 0xaf, 0x61, 0x6d, 0xfe, 0x94, 0xb6, 0x61, 0x25, 0x8c, 0xca, 0x29, 0x5e, 0x8b, 0x67,
	0x5b, 0xfa, 0x0e, 0x34, 0x4e, 0xf9, 0x54, 0x9a, 0x30, 0x2d, 0xbf, 0xa1, 0x5d, 0x58, 0x4d, 0x8e,
	0xb9, 0x48, 0x15, 0x16, 0xce, 0x80, 0xb5, 0x41, 0x75, 0x93, 0xc4, 0xf3, 0xd8, 0xce, 0x6f, 0x55,
	0x58, 0x9d, 0x49, 0xa1, 0xf9, 0xc2, 0x1c, 0xb3, 0xa6, 0x5a, 0xcb, 0x0e, 0x2f, 0xd7, 0x99, 0x57,
	0xbc, 0x7b, 0xb7, 0x30, 0xea, 0xc9, 0xdc, 0x66, 0xfe, 0x2f, 0xe5, 0x16, 0x5c, 0xf3, 0xae, 0x19,
	0x31, 0x33, 0x12, 0x4c, 0x9b, 0x11, 0x4e, 0x99, 0x08, 0xe7, 0xdf, 0xf4, 0x8f, 0xbe, 0x34, 0x07,
	0x4c, 0x9b, 0xbb, 0x53, 0x26, 0xe8, 0x16, 0xb4, 0xb8, 0x1e, 0xa5, 0x5c, 0xb3, 0xb1, 0xc0, 0xd4,
	0xb5, 0x79, 0x35, 0x06, 0xae, 0xef, 0x84, 0x48, 0xe7, 0x7b, 0x78, 0xfb, 0x6f, 0x94, 0xf6, 0xc5,
	0x3c, 0xc1, 0x27, 0xa1, 0x59, 0x76, 0x49, 0x8f, 0xa0, 0xb1, 0xb0, 0x75, 0xab, 0xbf, 0x77, 0xf9,
	0x17, 0x32, 0xf6, 0x40, 0x7b, 0xd5, 0x4f, 0xc9, 0xe0, 0x87, 0xa7, 0x2f, 0xba, 0x95, 0x3f, 0x5e,
	0x74, 0xc9, 0x4f, 0x2f, 0xbb, 0x95, 0x67, 0x2f, 0xbb, 0x15, 0xf8, 0x28, 0x91, 0xf9, 0x7f, 0xc0,
	0x1e, 0x6c, 0x0c, 0x67, 0xe0, 0x47, 0xf6, 0xd2, 0xa0, 0x1f, 0xdf, 0x3e, 0x77, 0xc9, 0x18, 0xeb,
	0xbc, 0xe7, 0x4b, 0x7a, 0xff, 0x78, 0xf1, 0x19, 0x37, 0xdd, 0x8d, 0xe3, 0xf6, 0x5f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xf4, 0xf0, 0x9f, 0x7d, 0x20, 0x09, 0x00, 0x00,
}
