// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: common/observer/observer.proto

package observer // import "github.com/bsm/reason/common/observer"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import util "github.com/bsm/reason/util"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// ClassificationCategorical is a classification observer for categorical features.
type ClassificationCategorical struct {
	// Dist is a distribution by feature category.
	Dist                 util.Matrix `protobuf:"bytes,1,opt,name=dist" json:"dist"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
}

func (m *ClassificationCategorical) Reset()         { *m = ClassificationCategorical{} }
func (m *ClassificationCategorical) String() string { return proto.CompactTextString(m) }
func (*ClassificationCategorical) ProtoMessage()    {}
func (*ClassificationCategorical) Descriptor() ([]byte, []int) {
	return fileDescriptor_observer_72606f1a45a634d2, []int{0}
}
func (m *ClassificationCategorical) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassificationCategorical.Unmarshal(m, b)
}
func (m *ClassificationCategorical) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassificationCategorical.Marshal(b, m, deterministic)
}
func (dst *ClassificationCategorical) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassificationCategorical.Merge(dst, src)
}
func (m *ClassificationCategorical) XXX_Size() int {
	return xxx_messageInfo_ClassificationCategorical.Size(m)
}
func (m *ClassificationCategorical) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassificationCategorical.DiscardUnknown(m)
}

var xxx_messageInfo_ClassificationCategorical proto.InternalMessageInfo

// ClassificationNumerical is a classification observer for numeric features
// using gaussian estimators.
type ClassificationNumerical struct {
	// Dist is a distribution by target category.
	Dist                 util.NumStreams `protobuf:"bytes,1,opt,name=dist" json:"dist"`
	MaxBuckets           uint32          `protobuf:"varint,2,opt,name=max_buckets,json=maxBuckets,proto3" json:"max_buckets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
}

func (m *ClassificationNumerical) Reset()         { *m = ClassificationNumerical{} }
func (m *ClassificationNumerical) String() string { return proto.CompactTextString(m) }
func (*ClassificationNumerical) ProtoMessage()    {}
func (*ClassificationNumerical) Descriptor() ([]byte, []int) {
	return fileDescriptor_observer_72606f1a45a634d2, []int{1}
}
func (m *ClassificationNumerical) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassificationNumerical.Unmarshal(m, b)
}
func (m *ClassificationNumerical) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassificationNumerical.Marshal(b, m, deterministic)
}
func (dst *ClassificationNumerical) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassificationNumerical.Merge(dst, src)
}
func (m *ClassificationNumerical) XXX_Size() int {
	return xxx_messageInfo_ClassificationNumerical.Size(m)
}
func (m *ClassificationNumerical) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassificationNumerical.DiscardUnknown(m)
}

var xxx_messageInfo_ClassificationNumerical proto.InternalMessageInfo

// RegressionCategorical is a regression observer for categorical features.
type RegressionCategorical struct {
	// Dist is a distribution by feature category.
	Dist                 util.NumStreams `protobuf:"bytes,1,opt,name=dist" json:"dist"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
}

func (m *RegressionCategorical) Reset()         { *m = RegressionCategorical{} }
func (m *RegressionCategorical) String() string { return proto.CompactTextString(m) }
func (*RegressionCategorical) ProtoMessage()    {}
func (*RegressionCategorical) Descriptor() ([]byte, []int) {
	return fileDescriptor_observer_72606f1a45a634d2, []int{2}
}
func (m *RegressionCategorical) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegressionCategorical.Unmarshal(m, b)
}
func (m *RegressionCategorical) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegressionCategorical.Marshal(b, m, deterministic)
}
func (dst *RegressionCategorical) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegressionCategorical.Merge(dst, src)
}
func (m *RegressionCategorical) XXX_Size() int {
	return xxx_messageInfo_RegressionCategorical.Size(m)
}
func (m *RegressionCategorical) XXX_DiscardUnknown() {
	xxx_messageInfo_RegressionCategorical.DiscardUnknown(m)
}

var xxx_messageInfo_RegressionCategorical proto.InternalMessageInfo

// RegressionNumerical is a regression observer for numerical features.
type RegressionNumerical struct {
	Dist                 []RegressionNumerical_Bucket `protobuf:"bytes,1,rep,name=dist" json:"dist"`
	MaxBuckets           uint32                       `protobuf:"varint,2,opt,name=max_buckets,json=maxBuckets,proto3" json:"max_buckets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
}

func (m *RegressionNumerical) Reset()         { *m = RegressionNumerical{} }
func (m *RegressionNumerical) String() string { return proto.CompactTextString(m) }
func (*RegressionNumerical) ProtoMessage()    {}
func (*RegressionNumerical) Descriptor() ([]byte, []int) {
	return fileDescriptor_observer_72606f1a45a634d2, []int{3}
}
func (m *RegressionNumerical) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegressionNumerical.Unmarshal(m, b)
}
func (m *RegressionNumerical) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegressionNumerical.Marshal(b, m, deterministic)
}
func (dst *RegressionNumerical) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegressionNumerical.Merge(dst, src)
}
func (m *RegressionNumerical) XXX_Size() int {
	return xxx_messageInfo_RegressionNumerical.Size(m)
}
func (m *RegressionNumerical) XXX_DiscardUnknown() {
	xxx_messageInfo_RegressionNumerical.DiscardUnknown(m)
}

var xxx_messageInfo_RegressionNumerical proto.InternalMessageInfo

type RegressionNumerical_Bucket struct {
	Threshold            float64 `protobuf:"fixed64,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	util.NumStream       `protobuf:"bytes,2,opt,name=stream,embedded=stream" json:"stream"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
}

func (m *RegressionNumerical_Bucket) Reset()         { *m = RegressionNumerical_Bucket{} }
func (m *RegressionNumerical_Bucket) String() string { return proto.CompactTextString(m) }
func (*RegressionNumerical_Bucket) ProtoMessage()    {}
func (*RegressionNumerical_Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_observer_72606f1a45a634d2, []int{3, 0}
}
func (m *RegressionNumerical_Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegressionNumerical_Bucket.Unmarshal(m, b)
}
func (m *RegressionNumerical_Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegressionNumerical_Bucket.Marshal(b, m, deterministic)
}
func (dst *RegressionNumerical_Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegressionNumerical_Bucket.Merge(dst, src)
}
func (m *RegressionNumerical_Bucket) XXX_Size() int {
	return xxx_messageInfo_RegressionNumerical_Bucket.Size(m)
}
func (m *RegressionNumerical_Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_RegressionNumerical_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_RegressionNumerical_Bucket proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClassificationCategorical)(nil), "blacksquaremedia.reason.common.observer.ClassificationCategorical")
	proto.RegisterType((*ClassificationNumerical)(nil), "blacksquaremedia.reason.common.observer.ClassificationNumerical")
	proto.RegisterType((*RegressionCategorical)(nil), "blacksquaremedia.reason.common.observer.RegressionCategorical")
	proto.RegisterType((*RegressionNumerical)(nil), "blacksquaremedia.reason.common.observer.RegressionNumerical")
	proto.RegisterType((*RegressionNumerical_Bucket)(nil), "blacksquaremedia.reason.common.observer.RegressionNumerical.Bucket")
}

func init() {
	proto.RegisterFile("common/observer/observer.proto", fileDescriptor_observer_72606f1a45a634d2)
}

var fileDescriptor_observer_72606f1a45a634d2 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x3d, 0x6b, 0xe3, 0x30,
	0x18, 0xc7, 0xed, 0x5c, 0x08, 0x77, 0x32, 0x77, 0x07, 0x3e, 0x8e, 0xa6, 0xa1, 0x38, 0xc1, 0xb4,
	0xc4, 0x4b, 0x65, 0x48, 0xf7, 0x0e, 0xce, 0xd4, 0xa1, 0x69, 0x71, 0xb7, 0x86, 0x52, 0x64, 0x47,
	0x71, 0x44, 0xac, 0xa8, 0x91, 0xe4, 0x92, 0xa9, 0x73, 0xc7, 0x7e, 0xac, 0x8c, 0x19, 0x3b, 0x05,
	0x42, 0xbe, 0x48, 0xb1, 0x94, 0xe6, 0x8d, 0xbe, 0xa4, 0xd0, 0xc5, 0x3c, 0xfa, 0xa3, 0xe7, 0x67,
	0xfd, 0xec, 0x47, 0xc0, 0x89, 0x19, 0xa5, 0x6c, 0xe0, 0xb3, 0x48, 0x60, 0x7e, 0x8f, 0xf9, 0xb2,
	0x80, 0x77, 0x9c, 0x49, 0x66, 0xd7, 0xa3, 0x14, 0xc5, 0x7d, 0x31, 0xcc, 0x10, 0xc7, 0x14, 0x77,
	0x08, 0x82, 0x1c, 0x23, 0xc1, 0x06, 0x50, 0xf7, 0xc1, 0xd7, 0xed, 0x95, 0xe3, 0x84, 0xc8, 0x5e,
	0x16, 0xe5, 0xb9, 0x9f, 0xb0, 0x84, 0xf9, 0xaa, 0x3f, 0xca, 0xba, 0x6a, 0xa5, 0x16, 0xaa, 0xd2,
	0xdc, 0xca, 0xdf, 0x4c, 0x92, 0xd4, 0xcf, 0x1f, 0x3a, 0x70, 0xdb, 0x60, 0xbf, 0x99, 0x22, 0x21,
	0x48, 0x97, 0xc4, 0x48, 0x12, 0x36, 0x68, 0x22, 0x89, 0x13, 0xc6, 0x49, 0x8c, 0x52, 0xfb, 0x14,
	0x14, 0x3b, 0x44, 0xc8, 0xb2, 0x59, 0x33, 0x3d, 0xab, 0x71, 0x08, 0xdf, 0x3b, 0x94, 0xe2, 0x9d,
	0x23, 0xc9, 0xc9, 0x28, 0x28, 0x8e, 0xa7, 0x55, 0x23, 0x54, 0x7d, 0xee, 0x03, 0xd8, 0xdb, 0x84,
	0xb7, 0x32, 0x8a, 0x35, 0x3a, 0xd8, 0x40, 0x7b, 0x1f, 0xa3, 0x5b, 0x19, 0xbd, 0x92, 0x1c, 0x23,
	0x2a, 0xd6, 0xf1, 0x76, 0x15, 0x58, 0x14, 0x8d, 0x6e, 0xa3, 0x2c, 0xee, 0x63, 0x29, 0xca, 0x85,
	0x9a, 0xe9, 0xfd, 0x0e, 0x01, 0x45, 0xa3, 0x40, 0x27, 0x6e, 0x1b, 0xfc, 0x0f, 0x71, 0xc2, 0xb1,
	0x10, 0x5b, 0x62, 0xdf, 0xf0, 0x76, 0xf7, 0xb1, 0x00, 0xfe, 0xad, 0xe8, 0x2b, 0xb3, 0x9b, 0x25,
	0xfb, 0x87, 0x67, 0x35, 0x9a, 0x70, 0xc7, 0x3f, 0x09, 0xdf, 0x60, 0x41, 0x2d, 0xf2, 0x25, 0xe9,
	0xca, 0x10, 0x94, 0x74, 0x69, 0x1f, 0x80, 0x5f, 0xb2, 0xc7, 0xb1, 0xe8, 0xb1, 0xb4, 0xa3, 0x54,
	0xcd, 0x70, 0x15, 0xd8, 0x67, 0xa0, 0x24, 0x94, 0x96, 0x62, 0x58, 0x8d, 0xfa, 0x8e, 0x5f, 0x21,
	0xf8, 0x99, 0x9f, 0x66, 0x32, 0xad, 0x9a, 0xe1, 0x02, 0x10, 0xf4, 0xc7, 0x33, 0xc7, 0x78, 0x9e,
	0x39, 0xe6, 0xd3, 0xdc, 0x31, 0x26, 0x73, 0xc7, 0x00, 0x6e, 0xcc, 0xe8, 0x27, 0xe6, 0xc1, 0x9f,
	0x8b, 0x85, 0xfa, 0x65, 0x3e, 0x89, 0xe2, 0xfa, 0x68, 0x6d, 0x94, 0x23, 0x41, 0x7d, 0xbd, 0xdb,
	0xdf, 0xba, 0x29, 0x51, 0x49, 0x0d, 0xee, 0xc9, 0x4b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93, 0x70,
	0xf9, 0x16, 0x43, 0x03, 0x00, 0x00,
}
