// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: classifier/bayes/internal/internal.proto

package internal // import "github.com/bsm/reason/classifier/ftrl/internal"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import reason "github.com/bsm/reason"
import observer "github.com/bsm/reason/common/observer"
import util "github.com/bsm/reason/util"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// NaiveBayes wraps a Naive Bayes classifier.
type NaiveBayes struct {
	// The underlying model.
	Model *reason.Model `protobuf:"bytes,1,opt,name=model" json:"model,omitempty"`
	// The target feature.
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Stats, by target category.
	TargetStats util.Vector `protobuf:"bytes,3,opt,name=target_stats,json=targetStats" json:"target_stats"`
	// Observer stats, by feature.
	FeatureStats         map[string]*NaiveBayes_Observer `protobuf:"bytes,4,rep,name=feature_stats,json=featureStats" json:"feature_stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
}

func (m *NaiveBayes) Reset()         { *m = NaiveBayes{} }
func (m *NaiveBayes) String() string { return proto.CompactTextString(m) }
func (*NaiveBayes) ProtoMessage()    {}
func (*NaiveBayes) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_1496cd1f2afbe13d, []int{0}
}
func (m *NaiveBayes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NaiveBayes.Unmarshal(m, b)
}
func (m *NaiveBayes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NaiveBayes.Marshal(b, m, deterministic)
}
func (dst *NaiveBayes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NaiveBayes.Merge(dst, src)
}
func (m *NaiveBayes) XXX_Size() int {
	return xxx_messageInfo_NaiveBayes.Size(m)
}
func (m *NaiveBayes) XXX_DiscardUnknown() {
	xxx_messageInfo_NaiveBayes.DiscardUnknown(m)
}

var xxx_messageInfo_NaiveBayes proto.InternalMessageInfo

// Observer instances maintain information based on
// observation of a particular feature.
type NaiveBayes_Observer struct {
	// Types that are valid to be assigned to Kind:
	//	*NaiveBayes_Observer_Num
	//	*NaiveBayes_Observer_Cat
	Kind                 isNaiveBayes_Observer_Kind `protobuf_oneof:"kind"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
}

func (m *NaiveBayes_Observer) Reset()         { *m = NaiveBayes_Observer{} }
func (m *NaiveBayes_Observer) String() string { return proto.CompactTextString(m) }
func (*NaiveBayes_Observer) ProtoMessage()    {}
func (*NaiveBayes_Observer) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_1496cd1f2afbe13d, []int{0, 0}
}
func (m *NaiveBayes_Observer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NaiveBayes_Observer.Unmarshal(m, b)
}
func (m *NaiveBayes_Observer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NaiveBayes_Observer.Marshal(b, m, deterministic)
}
func (dst *NaiveBayes_Observer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NaiveBayes_Observer.Merge(dst, src)
}
func (m *NaiveBayes_Observer) XXX_Size() int {
	return xxx_messageInfo_NaiveBayes_Observer.Size(m)
}
func (m *NaiveBayes_Observer) XXX_DiscardUnknown() {
	xxx_messageInfo_NaiveBayes_Observer.DiscardUnknown(m)
}

var xxx_messageInfo_NaiveBayes_Observer proto.InternalMessageInfo

type isNaiveBayes_Observer_Kind interface {
	isNaiveBayes_Observer_Kind()
}

type NaiveBayes_Observer_Num struct {
	Num *observer.ClassificationNumerical `protobuf:"bytes,1,opt,name=num,oneof"`
}
type NaiveBayes_Observer_Cat struct {
	Cat *observer.ClassificationCategorical `protobuf:"bytes,2,opt,name=cat,oneof"`
}

func (*NaiveBayes_Observer_Num) isNaiveBayes_Observer_Kind() {}
func (*NaiveBayes_Observer_Cat) isNaiveBayes_Observer_Kind() {}

func (m *NaiveBayes_Observer) GetKind() isNaiveBayes_Observer_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *NaiveBayes_Observer) GetNum() *observer.ClassificationNumerical {
	if x, ok := m.GetKind().(*NaiveBayes_Observer_Num); ok {
		return x.Num
	}
	return nil
}

func (m *NaiveBayes_Observer) GetCat() *observer.ClassificationCategorical {
	if x, ok := m.GetKind().(*NaiveBayes_Observer_Cat); ok {
		return x.Cat
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NaiveBayes_Observer) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _NaiveBayes_Observer_OneofMarshaler, _NaiveBayes_Observer_OneofUnmarshaler, _NaiveBayes_Observer_OneofSizer, []interface{}{
		(*NaiveBayes_Observer_Num)(nil),
		(*NaiveBayes_Observer_Cat)(nil),
	}
}

func _NaiveBayes_Observer_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*NaiveBayes_Observer)
	// kind
	switch x := m.Kind.(type) {
	case *NaiveBayes_Observer_Num:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Num); err != nil {
			return err
		}
	case *NaiveBayes_Observer_Cat:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Cat); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("NaiveBayes_Observer.Kind has unexpected type %T", x)
	}
	return nil
}

func _NaiveBayes_Observer_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*NaiveBayes_Observer)
	switch tag {
	case 1: // kind.num
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(observer.ClassificationNumerical)
		err := b.DecodeMessage(msg)
		m.Kind = &NaiveBayes_Observer_Num{msg}
		return true, err
	case 2: // kind.cat
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(observer.ClassificationCategorical)
		err := b.DecodeMessage(msg)
		m.Kind = &NaiveBayes_Observer_Cat{msg}
		return true, err
	default:
		return false, nil
	}
}

func _NaiveBayes_Observer_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*NaiveBayes_Observer)
	// kind
	switch x := m.Kind.(type) {
	case *NaiveBayes_Observer_Num:
		s := proto.Size(x.Num)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *NaiveBayes_Observer_Cat:
		s := proto.Size(x.Cat)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*NaiveBayes)(nil), "blacksquaremedia.reason.classifier.bayes.NaiveBayes")
	proto.RegisterMapType((map[string]*NaiveBayes_Observer)(nil), "blacksquaremedia.reason.classifier.bayes.NaiveBayes.FeatureStatsEntry")
	proto.RegisterType((*NaiveBayes_Observer)(nil), "blacksquaremedia.reason.classifier.bayes.NaiveBayes.Observer")
}

func init() {
	proto.RegisterFile("classifier/bayes/internal/internal.proto", fileDescriptor_internal_1496cd1f2afbe13d)
}

var fileDescriptor_internal_1496cd1f2afbe13d = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x93, 0x4d, 0xb7, 0xb8, 0x93, 0x8a, 0x3a, 0x07, 0x29, 0x3d, 0xc4, 0x22, 0x22, 0xb9,
	0x38, 0x81, 0xea, 0x41, 0x04, 0x41, 0xb2, 0xb8, 0x78, 0xd9, 0x55, 0xb2, 0xb2, 0x07, 0x2f, 0x32,
	0x99, 0xbe, 0xc4, 0xa1, 0x99, 0x8c, 0xce, 0x8f, 0x42, 0x2f, 0xfe, 0x0d, 0xfe, 0x49, 0x1e, 0xf7,
	0xe8, 0x51, 0x2f, 0xc2, 0xb2, 0xff, 0x88, 0x64, 0x32, 0xb6, 0x85, 0xa5, 0xb0, 0xf4, 0x12, 0xde,
	0x7b, 0x79, 0xef, 0xf3, 0xe6, 0x7d, 0xe7, 0x0d, 0x4a, 0x59, 0x43, 0xb5, 0xe6, 0x15, 0x07, 0x95,
	0x95, 0x74, 0x05, 0x3a, 0xe3, 0xad, 0x01, 0xd5, 0xd2, 0x66, 0x6d, 0x90, 0xaf, 0x4a, 0x1a, 0x89,
	0xd3, 0xb2, 0xa1, 0x6c, 0xa1, 0xbf, 0x59, 0xaa, 0x40, 0xc0, 0x9c, 0x53, 0xa2, 0x80, 0x6a, 0xd9,
	0x92, 0x0d, 0x81, 0x38, 0xc2, 0x64, 0xe4, 0x7f, 0xb8, 0xba, 0xc9, 0x3d, 0x6b, 0x78, 0x93, 0x75,
	0x1f, 0x1f, 0x48, 0x98, 0x14, 0x42, 0xb6, 0x99, 0x2c, 0x35, 0xa8, 0x25, 0xa8, 0xb5, 0xe1, 0xff,
	0x3f, 0xab, 0xb9, 0xf9, 0x62, 0x4b, 0xc2, 0xa4, 0xc8, 0x6a, 0x59, 0xcb, 0xcc, 0x85, 0x4b, 0x5b,
	0x39, 0xcf, 0x39, 0xce, 0xea, 0xd3, 0x1f, 0xff, 0x19, 0x20, 0x74, 0x46, 0xf9, 0x12, 0xf2, 0xae,
	0x39, 0x7e, 0x81, 0x0e, 0x85, 0x9c, 0x43, 0x33, 0x0e, 0xa7, 0x61, 0x1a, 0xcf, 0x12, 0xb2, 0xeb,
	0xd8, 0xa7, 0x5d, 0x56, 0xd1, 0x27, 0xe3, 0x87, 0x68, 0x68, 0xa8, 0xaa, 0xc1, 0x8c, 0x0f, 0xa6,
	0x61, 0x7a, 0x54, 0x78, 0x0f, 0x9f, 0xa2, 0x51, 0x6f, 0x7d, 0xd6, 0x86, 0x1a, 0x3d, 0x8e, 0x1c,
	0xf4, 0xc9, 0x4e, 0xa8, 0x1b, 0xf3, 0x02, 0x98, 0x91, 0x2a, 0x1f, 0x5c, 0xfe, 0x7d, 0x14, 0x14,
	0x71, 0x5f, 0x7f, 0xde, 0x95, 0xe3, 0x05, 0xba, 0x5b, 0x01, 0x35, 0x56, 0x81, 0xe7, 0x0d, 0xa6,
	0x51, 0x1a, 0xcf, 0x4e, 0xc8, 0x6d, 0xb5, 0x25, 0x9b, 0x49, 0xc9, 0x49, 0x4f, 0x72, 0xe4, 0xb7,
	0xad, 0x51, 0xab, 0x62, 0x54, 0x6d, 0x85, 0x26, 0x3f, 0x43, 0x74, 0xe7, 0xbd, 0x97, 0x16, 0x7f,
	0x44, 0x51, 0x6b, 0x85, 0x17, 0xe5, 0xcd, 0xee, 0x7e, 0xee, 0x6a, 0xc8, 0xfa, 0x46, 0x8e, 0x7d,
	0x7f, 0x46, 0x0d, 0x97, 0xed, 0x99, 0x15, 0xa0, 0x38, 0xa3, 0xcd, 0xbb, 0xa0, 0xe8, 0x70, 0xf8,
	0x02, 0x45, 0x8c, 0xf6, 0x9a, 0xc5, 0xb3, 0x7c, 0x4f, 0xea, 0x31, 0x35, 0x50, 0xcb, 0x35, 0x97,
	0x51, 0x93, 0x0f, 0xd1, 0x60, 0xc1, 0xdb, 0xf9, 0xe4, 0x3b, 0x7a, 0x70, 0x63, 0x4a, 0x7c, 0x1f,
	0x45, 0x0b, 0x58, 0xb9, 0x51, 0x8e, 0x8a, 0xce, 0xc4, 0xe7, 0xe8, 0x70, 0x49, 0x1b, 0x0b, 0xfe,
	0x20, 0xaf, 0xf7, 0x92, 0xf3, 0xbf, 0x54, 0x45, 0xcf, 0x7a, 0x75, 0xf0, 0x32, 0xcc, 0xed, 0xe5,
	0x55, 0x12, 0xfc, 0xbe, 0x4a, 0xc2, 0x1f, 0xd7, 0x49, 0xf0, 0xeb, 0x3a, 0x09, 0xd0, 0x53, 0x26,
	0xc5, 0x2d, 0xf0, 0x79, 0xec, 0xa0, 0x1f, 0xba, 0x0d, 0xd5, 0x9f, 0xc8, 0xd6, 0x46, 0x97, 0x5a,
	0x64, 0x7d, 0x7a, 0xb6, 0xf5, 0xf4, 0x2a, 0xa3, 0x36, 0x0f, 0xae, 0x1c, 0xba, 0xcd, 0x7e, 0xfe,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xe2, 0x16, 0xfe, 0x9d, 0x03, 0x00, 0x00,
}
